// Code generated by ent, DO NOT EDIT.

package auditlog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the auditlog type in the database.
	Label = "audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccessRequestID holds the string denoting the access_request_id field in the database.
	FieldAccessRequestID = "access_request_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldActorEmail holds the string denoting the actor_email field in the database.
	FieldActorEmail = "actor_email"
	// FieldActorRole holds the string denoting the actor_role field in the database.
	FieldActorRole = "actor_role"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccessRequest holds the string denoting the access_request edge name in mutations.
	EdgeAccessRequest = "access_request"
	// Table holds the table name of the auditlog in the database.
	Table = "audit_logs"
	// AccessRequestTable is the table that holds the access_request relation/edge.
	AccessRequestTable = "audit_logs"
	// AccessRequestInverseTable is the table name for the AccessRequest entity.
	// It exists in this package in order to avoid circular dependency with the "accessrequest" package.
	AccessRequestInverseTable = "access_requests"
	// AccessRequestColumn is the table column denoting the access_request relation/edge.
	AccessRequestColumn = "access_request_id"
)

// Columns holds all SQL columns for auditlog fields.
var Columns = []string{
	FieldID,
	FieldAccessRequestID,
	FieldAction,
	FieldActorEmail,
	FieldActorRole,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActorEmailValidator is a validator for the "actor_email" field. It is called by the builders before save.
	ActorEmailValidator func(string) error
	// ActorRoleValidator is a validator for the "actor_role" field. It is called by the builders before save.
	ActorRoleValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Action defines the type for the "action" enum field.
type Action string

// Action values.
const (
	ActionREQUEST_CREATED      Action = "REQUEST_CREATED"
	ActionREQUEST_APPROVED     Action = "REQUEST_APPROVED"
	ActionREQUEST_REJECTED     Action = "REQUEST_REJECTED"
	ActionREQUEST_UNDER_REVIEW Action = "REQUEST_UNDER_REVIEW"
	ActionCOMMENT_ADDED        Action = "COMMENT_ADDED"
	ActionSCREENSHOT_UPLOADED  Action = "SCREENSHOT_UPLOADED"
	ActionUSER_CREATED         Action = "USER_CREATED"
	ActionUSER_ROLE_CHANGED    Action = "USER_ROLE_CHANGED"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionREQUEST_CREATED, ActionREQUEST_APPROVED, ActionREQUEST_REJECTED, ActionREQUEST_UNDER_REVIEW, ActionCOMMENT_ADDED, ActionSCREENSHOT_UPLOADED, ActionUSER_CREATED, ActionUSER_ROLE_CHANGED:
		return nil
	default:
		return fmt.Errorf("auditlog: invalid enum value for action field: %q", a)
	}
}

// OrderOption defines the ordering options for the AuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccessRequestID orders the results by the access_request_id field.
func ByAccessRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessRequestID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByActorEmail orders the results by the actor_email field.
func ByActorEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorEmail, opts...).ToFunc()
}

// ByActorRole orders the results by the actor_role field.
func ByActorRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorRole, opts...).ToFunc()
}

// ByMetadata orders the results by the metadata field.
func ByMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadata, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAccessRequestField orders the results by access_request field.
func ByAccessRequestField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccessRequestStep(), sql.OrderByField(field, opts...))
	}
}
func newAccessRequestStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccessRequestInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccessRequestTable, AccessRequestColumn),
	)
}
