// Code generated by ent, DO NOT EDIT.

package auditlog

import (
	"cerberus/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldID, id))
}

// AccessRequestID applies equality check predicate on the "access_request_id" field. It's identical to AccessRequestIDEQ.
func AccessRequestID(v int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldAccessRequestID, v))
}

// ActorEmail applies equality check predicate on the "actor_email" field. It's identical to ActorEmailEQ.
func ActorEmail(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldActorEmail, v))
}

// ActorRole applies equality check predicate on the "actor_role" field. It's identical to ActorRoleEQ.
func ActorRole(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldActorRole, v))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldMetadata, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// AccessRequestIDEQ applies the EQ predicate on the "access_request_id" field.
func AccessRequestIDEQ(v int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldAccessRequestID, v))
}

// AccessRequestIDNEQ applies the NEQ predicate on the "access_request_id" field.
func AccessRequestIDNEQ(v int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldAccessRequestID, v))
}

// AccessRequestIDIn applies the In predicate on the "access_request_id" field.
func AccessRequestIDIn(vs ...int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldAccessRequestID, vs...))
}

// AccessRequestIDNotIn applies the NotIn predicate on the "access_request_id" field.
func AccessRequestIDNotIn(vs ...int) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldAccessRequestID, vs...))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v Action) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v Action) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...Action) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...Action) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldAction, vs...))
}

// ActorEmailEQ applies the EQ predicate on the "actor_email" field.
func ActorEmailEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldActorEmail, v))
}

// ActorEmailNEQ applies the NEQ predicate on the "actor_email" field.
func ActorEmailNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldActorEmail, v))
}

// ActorEmailIn applies the In predicate on the "actor_email" field.
func ActorEmailIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldActorEmail, vs...))
}

// ActorEmailNotIn applies the NotIn predicate on the "actor_email" field.
func ActorEmailNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldActorEmail, vs...))
}

// ActorEmailGT applies the GT predicate on the "actor_email" field.
func ActorEmailGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldActorEmail, v))
}

// ActorEmailGTE applies the GTE predicate on the "actor_email" field.
func ActorEmailGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldActorEmail, v))
}

// ActorEmailLT applies the LT predicate on the "actor_email" field.
func ActorEmailLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldActorEmail, v))
}

// ActorEmailLTE applies the LTE predicate on the "actor_email" field.
func ActorEmailLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldActorEmail, v))
}

// ActorEmailContains applies the Contains predicate on the "actor_email" field.
func ActorEmailContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldActorEmail, v))
}

// ActorEmailHasPrefix applies the HasPrefix predicate on the "actor_email" field.
func ActorEmailHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldActorEmail, v))
}

// ActorEmailHasSuffix applies the HasSuffix predicate on the "actor_email" field.
func ActorEmailHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldActorEmail, v))
}

// ActorEmailEqualFold applies the EqualFold predicate on the "actor_email" field.
func ActorEmailEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldActorEmail, v))
}

// ActorEmailContainsFold applies the ContainsFold predicate on the "actor_email" field.
func ActorEmailContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldActorEmail, v))
}

// ActorRoleEQ applies the EQ predicate on the "actor_role" field.
func ActorRoleEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldActorRole, v))
}

// ActorRoleNEQ applies the NEQ predicate on the "actor_role" field.
func ActorRoleNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldActorRole, v))
}

// ActorRoleIn applies the In predicate on the "actor_role" field.
func ActorRoleIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldActorRole, vs...))
}

// ActorRoleNotIn applies the NotIn predicate on the "actor_role" field.
func ActorRoleNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldActorRole, vs...))
}

// ActorRoleGT applies the GT predicate on the "actor_role" field.
func ActorRoleGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldActorRole, v))
}

// ActorRoleGTE applies the GTE predicate on the "actor_role" field.
func ActorRoleGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldActorRole, v))
}

// ActorRoleLT applies the LT predicate on the "actor_role" field.
func ActorRoleLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldActorRole, v))
}

// ActorRoleLTE applies the LTE predicate on the "actor_role" field.
func ActorRoleLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldActorRole, v))
}

// ActorRoleContains applies the Contains predicate on the "actor_role" field.
func ActorRoleContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldActorRole, v))
}

// ActorRoleHasPrefix applies the HasPrefix predicate on the "actor_role" field.
func ActorRoleHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldActorRole, v))
}

// ActorRoleHasSuffix applies the HasSuffix predicate on the "actor_role" field.
func ActorRoleHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldActorRole, v))
}

// ActorRoleEqualFold applies the EqualFold predicate on the "actor_role" field.
func ActorRoleEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldActorRole, v))
}

// ActorRoleContainsFold applies the ContainsFold predicate on the "actor_role" field.
func ActorRoleContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldActorRole, v))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldMetadata, v))
}

// MetadataContains applies the Contains predicate on the "metadata" field.
func MetadataContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldMetadata, v))
}

// MetadataHasPrefix applies the HasPrefix predicate on the "metadata" field.
func MetadataHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldMetadata, v))
}

// MetadataHasSuffix applies the HasSuffix predicate on the "metadata" field.
func MetadataHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldMetadata, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldMetadata))
}

// MetadataEqualFold applies the EqualFold predicate on the "metadata" field.
func MetadataEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldMetadata, v))
}

// MetadataContainsFold applies the ContainsFold predicate on the "metadata" field.
func MetadataContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldMetadata, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAccessRequest applies the HasEdge predicate on the "access_request" edge.
func HasAccessRequest() predicate.AuditLog {
	return predicate.AuditLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccessRequestTable, AccessRequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccessRequestWith applies the HasEdge predicate on the "access_request" edge with a given conditions (other predicates).
func HasAccessRequestWith(preds ...predicate.AccessRequest) predicate.AuditLog {
	return predicate.AuditLog(func(s *sql.Selector) {
		step := newAccessRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditLog) predicate.AuditLog {
	return predicate.AuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditLog) predicate.AuditLog {
	return predicate.AuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditLog) predicate.AuditLog {
	return predicate.AuditLog(sql.NotPredicates(p))
}
