// Code generated by ent, DO NOT EDIT.

package accessrequest

import (
	"cerberus/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldID, id))
}

// RequesterID applies equality check predicate on the "requester_id" field. It's identical to RequesterIDEQ.
func RequesterID(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequesterID, v))
}

// ManagerID applies equality check predicate on the "manager_id" field. It's identical to ManagerIDEQ.
func ManagerID(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldManagerID, v))
}

// ReviewerID applies equality check predicate on the "reviewer_id" field. It's identical to ReviewerIDEQ.
func ReviewerID(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReviewerID, v))
}

// Resource applies equality check predicate on the "resource" field. It's identical to ResourceEQ.
func Resource(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldResource, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReason, v))
}

// ScreenshotURL applies equality check predicate on the "screenshot_url" field. It's identical to ScreenshotURLEQ.
func ScreenshotURL(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldScreenshotURL, v))
}

// ReviewComment applies equality check predicate on the "review_comment" field. It's identical to ReviewCommentEQ.
func ReviewComment(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReviewComment, v))
}

// ManagerEmail applies equality check predicate on the "manager_email" field. It's identical to ManagerEmailEQ.
func ManagerEmail(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldManagerEmail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldResolvedAt, v))
}

// RequesterIDEQ applies the EQ predicate on the "requester_id" field.
func RequesterIDEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequesterID, v))
}

// RequesterIDNEQ applies the NEQ predicate on the "requester_id" field.
func RequesterIDNEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldRequesterID, v))
}

// RequesterIDIn applies the In predicate on the "requester_id" field.
func RequesterIDIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldRequesterID, vs...))
}

// RequesterIDNotIn applies the NotIn predicate on the "requester_id" field.
func RequesterIDNotIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldRequesterID, vs...))
}

// ManagerIDEQ applies the EQ predicate on the "manager_id" field.
func ManagerIDEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldManagerID, v))
}

// ManagerIDNEQ applies the NEQ predicate on the "manager_id" field.
func ManagerIDNEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldManagerID, v))
}

// ManagerIDIn applies the In predicate on the "manager_id" field.
func ManagerIDIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldManagerID, vs...))
}

// ManagerIDNotIn applies the NotIn predicate on the "manager_id" field.
func ManagerIDNotIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldManagerID, vs...))
}

// ManagerIDIsNil applies the IsNil predicate on the "manager_id" field.
func ManagerIDIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldManagerID))
}

// ManagerIDNotNil applies the NotNil predicate on the "manager_id" field.
func ManagerIDNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldManagerID))
}

// ReviewerIDEQ applies the EQ predicate on the "reviewer_id" field.
func ReviewerIDEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReviewerID, v))
}

// ReviewerIDNEQ applies the NEQ predicate on the "reviewer_id" field.
func ReviewerIDNEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldReviewerID, v))
}

// ReviewerIDIn applies the In predicate on the "reviewer_id" field.
func ReviewerIDIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldReviewerID, vs...))
}

// ReviewerIDNotIn applies the NotIn predicate on the "reviewer_id" field.
func ReviewerIDNotIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldReviewerID, vs...))
}

// ReviewerIDIsNil applies the IsNil predicate on the "reviewer_id" field.
func ReviewerIDIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldReviewerID))
}

// ReviewerIDNotNil applies the NotNil predicate on the "reviewer_id" field.
func ReviewerIDNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldReviewerID))
}

// ResourceEQ applies the EQ predicate on the "resource" field.
func ResourceEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldResource, v))
}

// ResourceNEQ applies the NEQ predicate on the "resource" field.
func ResourceNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldResource, v))
}

// ResourceIn applies the In predicate on the "resource" field.
func ResourceIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldResource, vs...))
}

// ResourceNotIn applies the NotIn predicate on the "resource" field.
func ResourceNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldResource, vs...))
}

// ResourceGT applies the GT predicate on the "resource" field.
func ResourceGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldResource, v))
}

// ResourceGTE applies the GTE predicate on the "resource" field.
func ResourceGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldResource, v))
}

// ResourceLT applies the LT predicate on the "resource" field.
func ResourceLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldResource, v))
}

// ResourceLTE applies the LTE predicate on the "resource" field.
func ResourceLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldResource, v))
}

// ResourceContains applies the Contains predicate on the "resource" field.
func ResourceContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldResource, v))
}

// ResourceHasPrefix applies the HasPrefix predicate on the "resource" field.
func ResourceHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldResource, v))
}

// ResourceHasSuffix applies the HasSuffix predicate on the "resource" field.
func ResourceHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldResource, v))
}

// ResourceEqualFold applies the EqualFold predicate on the "resource" field.
func ResourceEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldResource, v))
}

// ResourceContainsFold applies the ContainsFold predicate on the "resource" field.
func ResourceContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldResource, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// ScreenshotURLEQ applies the EQ predicate on the "screenshot_url" field.
func ScreenshotURLEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldScreenshotURL, v))
}

// ScreenshotURLNEQ applies the NEQ predicate on the "screenshot_url" field.
func ScreenshotURLNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldScreenshotURL, v))
}

// ScreenshotURLIn applies the In predicate on the "screenshot_url" field.
func ScreenshotURLIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldScreenshotURL, vs...))
}

// ScreenshotURLNotIn applies the NotIn predicate on the "screenshot_url" field.
func ScreenshotURLNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldScreenshotURL, vs...))
}

// ScreenshotURLGT applies the GT predicate on the "screenshot_url" field.
func ScreenshotURLGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldScreenshotURL, v))
}

// ScreenshotURLGTE applies the GTE predicate on the "screenshot_url" field.
func ScreenshotURLGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldScreenshotURL, v))
}

// ScreenshotURLLT applies the LT predicate on the "screenshot_url" field.
func ScreenshotURLLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldScreenshotURL, v))
}

// ScreenshotURLLTE applies the LTE predicate on the "screenshot_url" field.
func ScreenshotURLLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldScreenshotURL, v))
}

// ScreenshotURLContains applies the Contains predicate on the "screenshot_url" field.
func ScreenshotURLContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldScreenshotURL, v))
}

// ScreenshotURLHasPrefix applies the HasPrefix predicate on the "screenshot_url" field.
func ScreenshotURLHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldScreenshotURL, v))
}

// ScreenshotURLHasSuffix applies the HasSuffix predicate on the "screenshot_url" field.
func ScreenshotURLHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldScreenshotURL, v))
}

// ScreenshotURLIsNil applies the IsNil predicate on the "screenshot_url" field.
func ScreenshotURLIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldScreenshotURL))
}

// ScreenshotURLNotNil applies the NotNil predicate on the "screenshot_url" field.
func ScreenshotURLNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldScreenshotURL))
}

// ScreenshotURLEqualFold applies the EqualFold predicate on the "screenshot_url" field.
func ScreenshotURLEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldScreenshotURL, v))
}

// ScreenshotURLContainsFold applies the ContainsFold predicate on the "screenshot_url" field.
func ScreenshotURLContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldScreenshotURL, v))
}

// ReviewCommentEQ applies the EQ predicate on the "review_comment" field.
func ReviewCommentEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReviewComment, v))
}

// ReviewCommentNEQ applies the NEQ predicate on the "review_comment" field.
func ReviewCommentNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldReviewComment, v))
}

// ReviewCommentIn applies the In predicate on the "review_comment" field.
func ReviewCommentIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldReviewComment, vs...))
}

// ReviewCommentNotIn applies the NotIn predicate on the "review_comment" field.
func ReviewCommentNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldReviewComment, vs...))
}

// ReviewCommentGT applies the GT predicate on the "review_comment" field.
func ReviewCommentGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldReviewComment, v))
}

// ReviewCommentGTE applies the GTE predicate on the "review_comment" field.
func ReviewCommentGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldReviewComment, v))
}

// ReviewCommentLT applies the LT predicate on the "review_comment" field.
func ReviewCommentLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldReviewComment, v))
}

// ReviewCommentLTE applies the LTE predicate on the "review_comment" field.
func ReviewCommentLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldReviewComment, v))
}

// ReviewCommentContains applies the Contains predicate on the "review_comment" field.
func ReviewCommentContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldReviewComment, v))
}

// ReviewCommentHasPrefix applies the HasPrefix predicate on the "review_comment" field.
func ReviewCommentHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldReviewComment, v))
}

// ReviewCommentHasSuffix applies the HasSuffix predicate on the "review_comment" field.
func ReviewCommentHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldReviewComment, v))
}

// ReviewCommentIsNil applies the IsNil predicate on the "review_comment" field.
func ReviewCommentIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldReviewComment))
}

// ReviewCommentNotNil applies the NotNil predicate on the "review_comment" field.
func ReviewCommentNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldReviewComment))
}

// ReviewCommentEqualFold applies the EqualFold predicate on the "review_comment" field.
func ReviewCommentEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldReviewComment, v))
}

// ReviewCommentContainsFold applies the ContainsFold predicate on the "review_comment" field.
func ReviewCommentContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldReviewComment, v))
}

// ManagerEmailEQ applies the EQ predicate on the "manager_email" field.
func ManagerEmailEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldManagerEmail, v))
}

// ManagerEmailNEQ applies the NEQ predicate on the "manager_email" field.
func ManagerEmailNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldManagerEmail, v))
}

// ManagerEmailIn applies the In predicate on the "manager_email" field.
func ManagerEmailIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldManagerEmail, vs...))
}

// ManagerEmailNotIn applies the NotIn predicate on the "manager_email" field.
func ManagerEmailNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldManagerEmail, vs...))
}

// ManagerEmailGT applies the GT predicate on the "manager_email" field.
func ManagerEmailGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldManagerEmail, v))
}

// ManagerEmailGTE applies the GTE predicate on the "manager_email" field.
func ManagerEmailGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldManagerEmail, v))
}

// ManagerEmailLT applies the LT predicate on the "manager_email" field.
func ManagerEmailLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldManagerEmail, v))
}

// ManagerEmailLTE applies the LTE predicate on the "manager_email" field.
func ManagerEmailLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldManagerEmail, v))
}

// ManagerEmailContains applies the Contains predicate on the "manager_email" field.
func ManagerEmailContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldManagerEmail, v))
}

// ManagerEmailHasPrefix applies the HasPrefix predicate on the "manager_email" field.
func ManagerEmailHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldManagerEmail, v))
}

// ManagerEmailHasSuffix applies the HasSuffix predicate on the "manager_email" field.
func ManagerEmailHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldManagerEmail, v))
}

// ManagerEmailEqualFold applies the EqualFold predicate on the "manager_email" field.
func ManagerEmailEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldManagerEmail, v))
}

// ManagerEmailContainsFold applies the ContainsFold predicate on the "manager_email" field.
func ManagerEmailContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldManagerEmail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldResolvedAt))
}

// HasRequester applies the HasEdge predicate on the "requester" edge.
func HasRequester() predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RequesterTable, RequesterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequesterWith applies the HasEdge predicate on the "requester" edge with a given conditions (other predicates).
func HasRequesterWith(preds ...predicate.User) predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := newRequesterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasManager applies the HasEdge predicate on the "manager" edge.
func HasManager() predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ManagerTable, ManagerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManagerWith applies the HasEdge predicate on the "manager" edge with a given conditions (other predicates).
func HasManagerWith(preds ...predicate.User) predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := newManagerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviewer applies the HasEdge predicate on the "reviewer" edge.
func HasReviewer() predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReviewerTable, ReviewerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewerWith applies the HasEdge predicate on the "reviewer" edge with a given conditions (other predicates).
func HasReviewerWith(preds ...predicate.User) predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := newReviewerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuditLogs applies the HasEdge predicate on the "audit_logs" edge.
func HasAuditLogs() predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuditLogsTable, AuditLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditLogsWith applies the HasEdge predicate on the "audit_logs" edge with a given conditions (other predicates).
func HasAuditLogsWith(preds ...predicate.AuditLog) predicate.AccessRequest {
	return predicate.AccessRequest(func(s *sql.Selector) {
		step := newAuditLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccessRequest) predicate.AccessRequest {
	return predicate.AccessRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccessRequest) predicate.AccessRequest {
	return predicate.AccessRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccessRequest) predicate.AccessRequest {
	return predicate.AccessRequest(sql.NotPredicates(p))
}
