// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessRequestsColumns holds the columns for the "access_requests" table.
	AccessRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "resource", Type: field.TypeString},
		{Name: "reason", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "APPROVED", "REJECTED", "UNDER_REVIEW"}, Default: "PENDING"},
		{Name: "screenshot_url", Type: field.TypeString, Nullable: true},
		{Name: "review_comment", Type: field.TypeString, Nullable: true},
		{Name: "manager_email", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "resolved_at", Type: field.TypeTime, Nullable: true},
		{Name: "requester_id", Type: field.TypeInt},
		{Name: "manager_id", Type: field.TypeInt, Nullable: true},
		{Name: "reviewer_id", Type: field.TypeInt, Nullable: true},
	}
	// AccessRequestsTable holds the schema information for the "access_requests" table.
	AccessRequestsTable = &schema.Table{
		Name:       "access_requests",
		Columns:    AccessRequestsColumns,
		PrimaryKey: []*schema.Column{AccessRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "access_requests_users_submitted_requests",
				Columns:    []*schema.Column{AccessRequestsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "access_requests_users_managed_requests",
				Columns:    []*schema.Column{AccessRequestsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "access_requests_users_reviewed_requests",
				Columns:    []*schema.Column{AccessRequestsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "accessrequest_status",
				Unique:  false,
				Columns: []*schema.Column{AccessRequestsColumns[3]},
			},
			{
				Name:    "accessrequest_requester_id",
				Unique:  false,
				Columns: []*schema.Column{AccessRequestsColumns[10]},
			},
			{
				Name:    "accessrequest_manager_email",
				Unique:  false,
				Columns: []*schema.Column{AccessRequestsColumns[6]},
			},
			{
				Name:    "accessrequest_requester_id_status",
				Unique:  false,
				Columns: []*schema.Column{AccessRequestsColumns[10], AccessRequestsColumns[3]},
			},
			{
				Name:    "accessrequest_resource",
				Unique:  false,
				Columns: []*schema.Column{AccessRequestsColumns[1]},
			},
		},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"REQUEST_CREATED", "REQUEST_APPROVED", "REQUEST_REJECTED", "REQUEST_UNDER_REVIEW", "COMMENT_ADDED", "SCREENSHOT_UPLOADED", "USER_CREATED", "USER_ROLE_CHANGED"}},
		{Name: "actor_email", Type: field.TypeString},
		{Name: "actor_role", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "access_request_id", Type: field.TypeInt},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_logs_access_requests_audit_logs",
				Columns:    []*schema.Column{AuditLogsColumns[6]},
				RefColumns: []*schema.Column{AccessRequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_actor_email",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[2]},
			},
			{
				Name:    "auditlog_action",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[1]},
			},
			{
				Name:    "auditlog_access_request_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[6]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"EMPLOYEE", "APPROVER", "MANAGER", "ADMIN", "SUPER_ADMIN"}, Default: "EMPLOYEE"},
		{Name: "department", Type: field.TypeEnum, Nullable: true, Enums: []string{"ENGINEERING", "SUPPORT", "FINANCE", "HR", "SALES"}},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_role",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
			{
				Name:    "user_department",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessRequestsTable,
		AuditLogsTable,
		UsersTable,
	}
)

func init() {
	AccessRequestsTable.ForeignKeys[0].RefTable = UsersTable
	AccessRequestsTable.ForeignKeys[1].RefTable = UsersTable
	AccessRequestsTable.ForeignKeys[2].RefTable = UsersTable
	AuditLogsTable.ForeignKeys[0].RefTable = AccessRequestsTable
}
