// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessRequestDelete is the builder for deleting a AccessRequest entity.
type AccessRequestDelete struct {
	config
	hooks    []Hook
	mutation *AccessRequestMutation
}

// Where appends a list predicates to the AccessRequestDelete builder.
func (_d *AccessRequestDelete) Where(ps ...predicate.AccessRequest) *AccessRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccessRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccessRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accessrequest.Table, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccessRequestDeleteOne is the builder for deleting a single AccessRequest entity.
type AccessRequestDeleteOne struct {
	_d *AccessRequestDelete
}

// Where appends a list predicates to the AccessRequestDelete builder.
func (_d *AccessRequestDeleteOne) Where(ps ...predicate.AccessRequest) *AccessRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccessRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accessrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
