// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/auditlog"
	"cerberus/ent/predicate"
	"cerberus/ent/user"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessRequestQuery is the builder for querying AccessRequest entities.
type AccessRequestQuery struct {
	config
	ctx           *QueryContext
	order         []accessrequest.OrderOption
	inters        []Interceptor
	predicates    []predicate.AccessRequest
	withRequester *UserQuery
	withManager   *UserQuery
	withReviewer  *UserQuery
	withAuditLogs *AuditLogQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessRequestQuery builder.
func (_q *AccessRequestQuery) Where(ps ...predicate.AccessRequest) *AccessRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AccessRequestQuery) Limit(limit int) *AccessRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AccessRequestQuery) Offset(offset int) *AccessRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AccessRequestQuery) Unique(unique bool) *AccessRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AccessRequestQuery) Order(o ...accessrequest.OrderOption) *AccessRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRequester chains the current query on the "requester" edge.
func (_q *AccessRequestQuery) QueryRequester() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accessrequest.Table, accessrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accessrequest.RequesterTable, accessrequest.RequesterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManager chains the current query on the "manager" edge.
func (_q *AccessRequestQuery) QueryManager() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accessrequest.Table, accessrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accessrequest.ManagerTable, accessrequest.ManagerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReviewer chains the current query on the "reviewer" edge.
func (_q *AccessRequestQuery) QueryReviewer() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accessrequest.Table, accessrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accessrequest.ReviewerTable, accessrequest.ReviewerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAuditLogs chains the current query on the "audit_logs" edge.
func (_q *AccessRequestQuery) QueryAuditLogs() *AuditLogQuery {
	query := (&AuditLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accessrequest.Table, accessrequest.FieldID, selector),
			sqlgraph.To(auditlog.Table, auditlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accessrequest.AuditLogsTable, accessrequest.AuditLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessRequest entity from the query.
// Returns a *NotFoundError when no AccessRequest was found.
func (_q *AccessRequestQuery) First(ctx context.Context) (*AccessRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accessrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AccessRequestQuery) FirstX(ctx context.Context) *AccessRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessRequest ID from the query.
// Returns a *NotFoundError when no AccessRequest ID was found.
func (_q *AccessRequestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accessrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AccessRequestQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccessRequest entity is found.
// Returns a *NotFoundError when no AccessRequest entities are found.
func (_q *AccessRequestQuery) Only(ctx context.Context) (*AccessRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accessrequest.Label}
	default:
		return nil, &NotSingularError{accessrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AccessRequestQuery) OnlyX(ctx context.Context) *AccessRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessRequest ID in the query.
// Returns a *NotSingularError when more than one AccessRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AccessRequestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accessrequest.Label}
	default:
		err = &NotSingularError{accessrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AccessRequestQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessRequests.
func (_q *AccessRequestQuery) All(ctx context.Context) ([]*AccessRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccessRequest, *AccessRequestQuery]()
	return withInterceptors[[]*AccessRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AccessRequestQuery) AllX(ctx context.Context) []*AccessRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessRequest IDs.
func (_q *AccessRequestQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(accessrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AccessRequestQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AccessRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AccessRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AccessRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AccessRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AccessRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AccessRequestQuery) Clone() *AccessRequestQuery {
	if _q == nil {
		return nil
	}
	return &AccessRequestQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]accessrequest.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.AccessRequest{}, _q.predicates...),
		withRequester: _q.withRequester.Clone(),
		withManager:   _q.withManager.Clone(),
		withReviewer:  _q.withReviewer.Clone(),
		withAuditLogs: _q.withAuditLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRequester tells the query-builder to eager-load the nodes that are connected to
// the "requester" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessRequestQuery) WithRequester(opts ...func(*UserQuery)) *AccessRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequester = query
	return _q
}

// WithManager tells the query-builder to eager-load the nodes that are connected to
// the "manager" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessRequestQuery) WithManager(opts ...func(*UserQuery)) *AccessRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withManager = query
	return _q
}

// WithReviewer tells the query-builder to eager-load the nodes that are connected to
// the "reviewer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessRequestQuery) WithReviewer(opts ...func(*UserQuery)) *AccessRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReviewer = query
	return _q
}

// WithAuditLogs tells the query-builder to eager-load the nodes that are connected to
// the "audit_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessRequestQuery) WithAuditLogs(opts ...func(*AuditLogQuery)) *AccessRequestQuery {
	query := (&AuditLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAuditLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequesterID int `json:"requester_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessRequest.Query().
//		GroupBy(accessrequest.FieldRequesterID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AccessRequestQuery) GroupBy(field string, fields ...string) *AccessRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccessRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = accessrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequesterID int `json:"requester_id,omitempty"`
//	}
//
//	client.AccessRequest.Query().
//		Select(accessrequest.FieldRequesterID).
//		Scan(ctx, &v)
func (_q *AccessRequestQuery) Select(fields ...string) *AccessRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AccessRequestSelect{AccessRequestQuery: _q}
	sbuild.label = accessrequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccessRequestSelect configured with the given aggregations.
func (_q *AccessRequestQuery) Aggregate(fns ...AggregateFunc) *AccessRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AccessRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !accessrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AccessRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccessRequest, error) {
	var (
		nodes       = []*AccessRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withRequester != nil,
			_q.withManager != nil,
			_q.withReviewer != nil,
			_q.withAuditLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccessRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccessRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRequester; query != nil {
		if err := _q.loadRequester(ctx, query, nodes, nil,
			func(n *AccessRequest, e *User) { n.Edges.Requester = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withManager; query != nil {
		if err := _q.loadManager(ctx, query, nodes, nil,
			func(n *AccessRequest, e *User) { n.Edges.Manager = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReviewer; query != nil {
		if err := _q.loadReviewer(ctx, query, nodes, nil,
			func(n *AccessRequest, e *User) { n.Edges.Reviewer = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAuditLogs; query != nil {
		if err := _q.loadAuditLogs(ctx, query, nodes,
			func(n *AccessRequest) { n.Edges.AuditLogs = []*AuditLog{} },
			func(n *AccessRequest, e *AuditLog) { n.Edges.AuditLogs = append(n.Edges.AuditLogs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AccessRequestQuery) loadRequester(ctx context.Context, query *UserQuery, nodes []*AccessRequest, init func(*AccessRequest), assign func(*AccessRequest, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AccessRequest)
	for i := range nodes {
		fk := nodes[i].RequesterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "requester_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AccessRequestQuery) loadManager(ctx context.Context, query *UserQuery, nodes []*AccessRequest, init func(*AccessRequest), assign func(*AccessRequest, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AccessRequest)
	for i := range nodes {
		if nodes[i].ManagerID == nil {
			continue
		}
		fk := *nodes[i].ManagerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "manager_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AccessRequestQuery) loadReviewer(ctx context.Context, query *UserQuery, nodes []*AccessRequest, init func(*AccessRequest), assign func(*AccessRequest, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AccessRequest)
	for i := range nodes {
		if nodes[i].ReviewerID == nil {
			continue
		}
		fk := *nodes[i].ReviewerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reviewer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AccessRequestQuery) loadAuditLogs(ctx context.Context, query *AuditLogQuery, nodes []*AccessRequest, init func(*AccessRequest), assign func(*AccessRequest, *AuditLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AccessRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(auditlog.FieldAccessRequestID)
	}
	query.Where(predicate.AuditLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accessrequest.AuditLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AccessRequestID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "access_request_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AccessRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AccessRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accessrequest.Table, accessrequest.Columns, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessrequest.FieldID)
		for i := range fields {
			if fields[i] != accessrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRequester != nil {
			_spec.Node.AddColumnOnce(accessrequest.FieldRequesterID)
		}
		if _q.withManager != nil {
			_spec.Node.AddColumnOnce(accessrequest.FieldManagerID)
		}
		if _q.withReviewer != nil {
			_spec.Node.AddColumnOnce(accessrequest.FieldReviewerID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AccessRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(accessrequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = accessrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccessRequestGroupBy is the group-by builder for AccessRequest entities.
type AccessRequestGroupBy struct {
	selector
	build *AccessRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AccessRequestGroupBy) Aggregate(fns ...AggregateFunc) *AccessRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AccessRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessRequestQuery, *AccessRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AccessRequestGroupBy) sqlScan(ctx context.Context, root *AccessRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccessRequestSelect is the builder for selecting fields of AccessRequest entities.
type AccessRequestSelect struct {
	*AccessRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AccessRequestSelect) Aggregate(fns ...AggregateFunc) *AccessRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AccessRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessRequestQuery, *AccessRequestSelect](ctx, _s.AccessRequestQuery, _s, _s.inters, v)
}

func (_s *AccessRequestSelect) sqlScan(ctx context.Context, root *AccessRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
