// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/auditlog"
	"cerberus/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessRequestCreate is the builder for creating a AccessRequest entity.
type AccessRequestCreate struct {
	config
	mutation *AccessRequestMutation
	hooks    []Hook
}

// SetRequesterID sets the "requester_id" field.
func (_c *AccessRequestCreate) SetRequesterID(v int) *AccessRequestCreate {
	_c.mutation.SetRequesterID(v)
	return _c
}

// SetManagerID sets the "manager_id" field.
func (_c *AccessRequestCreate) SetManagerID(v int) *AccessRequestCreate {
	_c.mutation.SetManagerID(v)
	return _c
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableManagerID(v *int) *AccessRequestCreate {
	if v != nil {
		_c.SetManagerID(*v)
	}
	return _c
}

// SetReviewerID sets the "reviewer_id" field.
func (_c *AccessRequestCreate) SetReviewerID(v int) *AccessRequestCreate {
	_c.mutation.SetReviewerID(v)
	return _c
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableReviewerID(v *int) *AccessRequestCreate {
	if v != nil {
		_c.SetReviewerID(*v)
	}
	return _c
}

// SetResource sets the "resource" field.
func (_c *AccessRequestCreate) SetResource(v string) *AccessRequestCreate {
	_c.mutation.SetResource(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *AccessRequestCreate) SetReason(v string) *AccessRequestCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccessRequestCreate) SetStatus(v accessrequest.Status) *AccessRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableStatus(v *accessrequest.Status) *AccessRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetScreenshotURL sets the "screenshot_url" field.
func (_c *AccessRequestCreate) SetScreenshotURL(v string) *AccessRequestCreate {
	_c.mutation.SetScreenshotURL(v)
	return _c
}

// SetNillableScreenshotURL sets the "screenshot_url" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableScreenshotURL(v *string) *AccessRequestCreate {
	if v != nil {
		_c.SetScreenshotURL(*v)
	}
	return _c
}

// SetReviewComment sets the "review_comment" field.
func (_c *AccessRequestCreate) SetReviewComment(v string) *AccessRequestCreate {
	_c.mutation.SetReviewComment(v)
	return _c
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableReviewComment(v *string) *AccessRequestCreate {
	if v != nil {
		_c.SetReviewComment(*v)
	}
	return _c
}

// SetManagerEmail sets the "manager_email" field.
func (_c *AccessRequestCreate) SetManagerEmail(v string) *AccessRequestCreate {
	_c.mutation.SetManagerEmail(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessRequestCreate) SetCreatedAt(v time.Time) *AccessRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableCreatedAt(v *time.Time) *AccessRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccessRequestCreate) SetUpdatedAt(v time.Time) *AccessRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableUpdatedAt(v *time.Time) *AccessRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *AccessRequestCreate) SetResolvedAt(v time.Time) *AccessRequestCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *AccessRequestCreate) SetNillableResolvedAt(v *time.Time) *AccessRequestCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetRequester sets the "requester" edge to the User entity.
func (_c *AccessRequestCreate) SetRequester(v *User) *AccessRequestCreate {
	return _c.SetRequesterID(v.ID)
}

// SetManager sets the "manager" edge to the User entity.
func (_c *AccessRequestCreate) SetManager(v *User) *AccessRequestCreate {
	return _c.SetManagerID(v.ID)
}

// SetReviewer sets the "reviewer" edge to the User entity.
func (_c *AccessRequestCreate) SetReviewer(v *User) *AccessRequestCreate {
	return _c.SetReviewerID(v.ID)
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_c *AccessRequestCreate) AddAuditLogIDs(ids ...int) *AccessRequestCreate {
	_c.mutation.AddAuditLogIDs(ids...)
	return _c
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_c *AccessRequestCreate) AddAuditLogs(v ...*AuditLog) *AccessRequestCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditLogIDs(ids...)
}

// Mutation returns the AccessRequestMutation object of the builder.
func (_c *AccessRequestCreate) Mutation() *AccessRequestMutation {
	return _c.mutation
}

// Save creates the AccessRequest in the database.
func (_c *AccessRequestCreate) Save(ctx context.Context) (*AccessRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessRequestCreate) SaveX(ctx context.Context) *AccessRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessRequestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := accessrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accessrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accessrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessRequestCreate) check() error {
	if _, ok := _c.mutation.RequesterID(); !ok {
		return &ValidationError{Name: "requester_id", err: errors.New(`ent: missing required field "AccessRequest.requester_id"`)}
	}
	if _, ok := _c.mutation.Resource(); !ok {
		return &ValidationError{Name: "resource", err: errors.New(`ent: missing required field "AccessRequest.resource"`)}
	}
	if v, ok := _c.mutation.Resource(); ok {
		if err := accessrequest.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.resource": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "AccessRequest.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := accessrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccessRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := accessrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManagerEmail(); !ok {
		return &ValidationError{Name: "manager_email", err: errors.New(`ent: missing required field "AccessRequest.manager_email"`)}
	}
	if v, ok := _c.mutation.ManagerEmail(); ok {
		if err := accessrequest.ManagerEmailValidator(v); err != nil {
			return &ValidationError{Name: "manager_email", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.manager_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccessRequest.updated_at"`)}
	}
	if len(_c.mutation.RequesterIDs()) == 0 {
		return &ValidationError{Name: "requester", err: errors.New(`ent: missing required edge "AccessRequest.requester"`)}
	}
	return nil
}

func (_c *AccessRequestCreate) sqlSave(ctx context.Context) (*AccessRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessRequestCreate) createSpec() (*AccessRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accessrequest.Table, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Resource(); ok {
		_spec.SetField(accessrequest.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(accessrequest.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accessrequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ScreenshotURL(); ok {
		_spec.SetField(accessrequest.FieldScreenshotURL, field.TypeString, value)
		_node.ScreenshotURL = &value
	}
	if value, ok := _c.mutation.ReviewComment(); ok {
		_spec.SetField(accessrequest.FieldReviewComment, field.TypeString, value)
		_node.ReviewComment = &value
	}
	if value, ok := _c.mutation.ManagerEmail(); ok {
		_spec.SetField(accessrequest.FieldManagerEmail, field.TypeString, value)
		_node.ManagerEmail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accessrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accessrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(accessrequest.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if nodes := _c.mutation.RequesterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.RequesterTable,
			Columns: []string{accessrequest.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequesterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ManagerTable,
			Columns: []string{accessrequest.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ManagerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ReviewerTable,
			Columns: []string{accessrequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReviewerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessrequest.AuditLogsTable,
			Columns: []string{accessrequest.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccessRequestCreateBulk is the builder for creating many AccessRequest entities in bulk.
type AccessRequestCreateBulk struct {
	config
	err      error
	builders []*AccessRequestCreate
}

// Save creates the AccessRequest entities in the database.
func (_c *AccessRequestCreateBulk) Save(ctx context.Context) ([]*AccessRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessRequestCreateBulk) SaveX(ctx context.Context) []*AccessRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
