// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AccessRequest is the model entity for the AccessRequest schema.
type AccessRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RequesterID holds the value of the "requester_id" field.
	RequesterID int `json:"requester_id,omitempty"`
	// ManagerID holds the value of the "manager_id" field.
	ManagerID *int `json:"manager_id,omitempty"`
	// ReviewerID holds the value of the "reviewer_id" field.
	ReviewerID *int `json:"reviewer_id,omitempty"`
	// The system or resource access is being requested for
	Resource string `json:"resource,omitempty"`
	// Business justification for the request
	Reason string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status accessrequest.Status `json:"status,omitempty"`
	// S3 URL of the uploaded proof screenshot
	ScreenshotURL *string `json:"screenshot_url,omitempty"`
	// Comment left by reviewer during approval/rejection
	ReviewComment *string `json:"review_comment,omitempty"`
	// ManagerEmail holds the value of the "manager_email" field.
	ManagerEmail string `json:"manager_email,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// When the request was approved or rejected
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccessRequestQuery when eager-loading is set.
	Edges        AccessRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccessRequestEdges holds the relations/edges for other nodes in the graph.
type AccessRequestEdges struct {
	// Requester holds the value of the requester edge.
	Requester *User `json:"requester,omitempty"`
	// Manager holds the value of the manager edge.
	Manager *User `json:"manager,omitempty"`
	// Reviewer holds the value of the reviewer edge.
	Reviewer *User `json:"reviewer,omitempty"`
	// AuditLogs holds the value of the audit_logs edge.
	AuditLogs []*AuditLog `json:"audit_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// RequesterOrErr returns the Requester value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccessRequestEdges) RequesterOrErr() (*User, error) {
	if e.Requester != nil {
		return e.Requester, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "requester"}
}

// ManagerOrErr returns the Manager value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccessRequestEdges) ManagerOrErr() (*User, error) {
	if e.Manager != nil {
		return e.Manager, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "manager"}
}

// ReviewerOrErr returns the Reviewer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccessRequestEdges) ReviewerOrErr() (*User, error) {
	if e.Reviewer != nil {
		return e.Reviewer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reviewer"}
}

// AuditLogsOrErr returns the AuditLogs value or an error if the edge
// was not loaded in eager-loading.
func (e AccessRequestEdges) AuditLogsOrErr() ([]*AuditLog, error) {
	if e.loadedTypes[3] {
		return e.AuditLogs, nil
	}
	return nil, &NotLoadedError{edge: "audit_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accessrequest.FieldID, accessrequest.FieldRequesterID, accessrequest.FieldManagerID, accessrequest.FieldReviewerID:
			values[i] = new(sql.NullInt64)
		case accessrequest.FieldResource, accessrequest.FieldReason, accessrequest.FieldStatus, accessrequest.FieldScreenshotURL, accessrequest.FieldReviewComment, accessrequest.FieldManagerEmail:
			values[i] = new(sql.NullString)
		case accessrequest.FieldCreatedAt, accessrequest.FieldUpdatedAt, accessrequest.FieldResolvedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessRequest fields.
func (_m *AccessRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accessrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case accessrequest.FieldRequesterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requester_id", values[i])
			} else if value.Valid {
				_m.RequesterID = int(value.Int64)
			}
		case accessrequest.FieldManagerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field manager_id", values[i])
			} else if value.Valid {
				_m.ManagerID = new(int)
				*_m.ManagerID = int(value.Int64)
			}
		case accessrequest.FieldReviewerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewer_id", values[i])
			} else if value.Valid {
				_m.ReviewerID = new(int)
				*_m.ReviewerID = int(value.Int64)
			}
		case accessrequest.FieldResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource", values[i])
			} else if value.Valid {
				_m.Resource = value.String
			}
		case accessrequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case accessrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = accessrequest.Status(value.String)
			}
		case accessrequest.FieldScreenshotURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field screenshot_url", values[i])
			} else if value.Valid {
				_m.ScreenshotURL = new(string)
				*_m.ScreenshotURL = value.String
			}
		case accessrequest.FieldReviewComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_comment", values[i])
			} else if value.Valid {
				_m.ReviewComment = new(string)
				*_m.ReviewComment = value.String
			}
		case accessrequest.FieldManagerEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manager_email", values[i])
			} else if value.Valid {
				_m.ManagerEmail = value.String
			}
		case accessrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accessrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accessrequest.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessRequest.
// This includes values selected through modifiers, order, etc.
func (_m *AccessRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequester queries the "requester" edge of the AccessRequest entity.
func (_m *AccessRequest) QueryRequester() *UserQuery {
	return NewAccessRequestClient(_m.config).QueryRequester(_m)
}

// QueryManager queries the "manager" edge of the AccessRequest entity.
func (_m *AccessRequest) QueryManager() *UserQuery {
	return NewAccessRequestClient(_m.config).QueryManager(_m)
}

// QueryReviewer queries the "reviewer" edge of the AccessRequest entity.
func (_m *AccessRequest) QueryReviewer() *UserQuery {
	return NewAccessRequestClient(_m.config).QueryReviewer(_m)
}

// QueryAuditLogs queries the "audit_logs" edge of the AccessRequest entity.
func (_m *AccessRequest) QueryAuditLogs() *AuditLogQuery {
	return NewAccessRequestClient(_m.config).QueryAuditLogs(_m)
}

// Update returns a builder for updating this AccessRequest.
// Note that you need to call AccessRequest.Unwrap() before calling this method if this AccessRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccessRequest) Update() *AccessRequestUpdateOne {
	return NewAccessRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccessRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccessRequest) Unwrap() *AccessRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccessRequest) String() string {
	var builder strings.Builder
	builder.WriteString("AccessRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("requester_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequesterID))
	builder.WriteString(", ")
	if v := _m.ManagerID; v != nil {
		builder.WriteString("manager_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReviewerID; v != nil {
		builder.WriteString("reviewer_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("resource=")
	builder.WriteString(_m.Resource)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ScreenshotURL; v != nil {
		builder.WriteString("screenshot_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReviewComment; v != nil {
		builder.WriteString("review_comment=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("manager_email=")
	builder.WriteString(_m.ManagerEmail)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AccessRequests is a parsable slice of AccessRequest.
type AccessRequests []*AccessRequest
