// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/auditlog"
	"cerberus/ent/predicate"
	"cerberus/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessRequestUpdate is the builder for updating AccessRequest entities.
type AccessRequestUpdate struct {
	config
	hooks    []Hook
	mutation *AccessRequestMutation
}

// Where appends a list predicates to the AccessRequestUpdate builder.
func (_u *AccessRequestUpdate) Where(ps ...predicate.AccessRequest) *AccessRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequesterID sets the "requester_id" field.
func (_u *AccessRequestUpdate) SetRequesterID(v int) *AccessRequestUpdate {
	_u.mutation.SetRequesterID(v)
	return _u
}

// SetNillableRequesterID sets the "requester_id" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableRequesterID(v *int) *AccessRequestUpdate {
	if v != nil {
		_u.SetRequesterID(*v)
	}
	return _u
}

// SetManagerID sets the "manager_id" field.
func (_u *AccessRequestUpdate) SetManagerID(v int) *AccessRequestUpdate {
	_u.mutation.SetManagerID(v)
	return _u
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableManagerID(v *int) *AccessRequestUpdate {
	if v != nil {
		_u.SetManagerID(*v)
	}
	return _u
}

// ClearManagerID clears the value of the "manager_id" field.
func (_u *AccessRequestUpdate) ClearManagerID() *AccessRequestUpdate {
	_u.mutation.ClearManagerID()
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *AccessRequestUpdate) SetReviewerID(v int) *AccessRequestUpdate {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableReviewerID(v *int) *AccessRequestUpdate {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *AccessRequestUpdate) ClearReviewerID() *AccessRequestUpdate {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetResource sets the "resource" field.
func (_u *AccessRequestUpdate) SetResource(v string) *AccessRequestUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableResource(v *string) *AccessRequestUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *AccessRequestUpdate) SetReason(v string) *AccessRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableReason(v *string) *AccessRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccessRequestUpdate) SetStatus(v accessrequest.Status) *AccessRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableStatus(v *accessrequest.Status) *AccessRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScreenshotURL sets the "screenshot_url" field.
func (_u *AccessRequestUpdate) SetScreenshotURL(v string) *AccessRequestUpdate {
	_u.mutation.SetScreenshotURL(v)
	return _u
}

// SetNillableScreenshotURL sets the "screenshot_url" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableScreenshotURL(v *string) *AccessRequestUpdate {
	if v != nil {
		_u.SetScreenshotURL(*v)
	}
	return _u
}

// ClearScreenshotURL clears the value of the "screenshot_url" field.
func (_u *AccessRequestUpdate) ClearScreenshotURL() *AccessRequestUpdate {
	_u.mutation.ClearScreenshotURL()
	return _u
}

// SetReviewComment sets the "review_comment" field.
func (_u *AccessRequestUpdate) SetReviewComment(v string) *AccessRequestUpdate {
	_u.mutation.SetReviewComment(v)
	return _u
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableReviewComment(v *string) *AccessRequestUpdate {
	if v != nil {
		_u.SetReviewComment(*v)
	}
	return _u
}

// ClearReviewComment clears the value of the "review_comment" field.
func (_u *AccessRequestUpdate) ClearReviewComment() *AccessRequestUpdate {
	_u.mutation.ClearReviewComment()
	return _u
}

// SetManagerEmail sets the "manager_email" field.
func (_u *AccessRequestUpdate) SetManagerEmail(v string) *AccessRequestUpdate {
	_u.mutation.SetManagerEmail(v)
	return _u
}

// SetNillableManagerEmail sets the "manager_email" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableManagerEmail(v *string) *AccessRequestUpdate {
	if v != nil {
		_u.SetManagerEmail(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessRequestUpdate) SetUpdatedAt(v time.Time) *AccessRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *AccessRequestUpdate) SetResolvedAt(v time.Time) *AccessRequestUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *AccessRequestUpdate) SetNillableResolvedAt(v *time.Time) *AccessRequestUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *AccessRequestUpdate) ClearResolvedAt() *AccessRequestUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetRequester sets the "requester" edge to the User entity.
func (_u *AccessRequestUpdate) SetRequester(v *User) *AccessRequestUpdate {
	return _u.SetRequesterID(v.ID)
}

// SetManager sets the "manager" edge to the User entity.
func (_u *AccessRequestUpdate) SetManager(v *User) *AccessRequestUpdate {
	return _u.SetManagerID(v.ID)
}

// SetReviewer sets the "reviewer" edge to the User entity.
func (_u *AccessRequestUpdate) SetReviewer(v *User) *AccessRequestUpdate {
	return _u.SetReviewerID(v.ID)
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_u *AccessRequestUpdate) AddAuditLogIDs(ids ...int) *AccessRequestUpdate {
	_u.mutation.AddAuditLogIDs(ids...)
	return _u
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_u *AccessRequestUpdate) AddAuditLogs(v ...*AuditLog) *AccessRequestUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditLogIDs(ids...)
}

// Mutation returns the AccessRequestMutation object of the builder.
func (_u *AccessRequestUpdate) Mutation() *AccessRequestMutation {
	return _u.mutation
}

// ClearRequester clears the "requester" edge to the User entity.
func (_u *AccessRequestUpdate) ClearRequester() *AccessRequestUpdate {
	_u.mutation.ClearRequester()
	return _u
}

// ClearManager clears the "manager" edge to the User entity.
func (_u *AccessRequestUpdate) ClearManager() *AccessRequestUpdate {
	_u.mutation.ClearManager()
	return _u
}

// ClearReviewer clears the "reviewer" edge to the User entity.
func (_u *AccessRequestUpdate) ClearReviewer() *AccessRequestUpdate {
	_u.mutation.ClearReviewer()
	return _u
}

// ClearAuditLogs clears all "audit_logs" edges to the AuditLog entity.
func (_u *AccessRequestUpdate) ClearAuditLogs() *AccessRequestUpdate {
	_u.mutation.ClearAuditLogs()
	return _u
}

// RemoveAuditLogIDs removes the "audit_logs" edge to AuditLog entities by IDs.
func (_u *AccessRequestUpdate) RemoveAuditLogIDs(ids ...int) *AccessRequestUpdate {
	_u.mutation.RemoveAuditLogIDs(ids...)
	return _u
}

// RemoveAuditLogs removes "audit_logs" edges to AuditLog entities.
func (_u *AccessRequestUpdate) RemoveAuditLogs(v ...*AuditLog) *AccessRequestUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accessrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessRequestUpdate) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := accessrequest.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := accessrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accessrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagerEmail(); ok {
		if err := accessrequest.ManagerEmailValidator(v); err != nil {
			return &ValidationError{Name: "manager_email", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.manager_email": %w`, err)}
		}
	}
	if _u.mutation.RequesterCleared() && len(_u.mutation.RequesterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccessRequest.requester"`)
	}
	return nil
}

func (_u *AccessRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessrequest.Table, accessrequest.Columns, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(accessrequest.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(accessrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accessrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScreenshotURL(); ok {
		_spec.SetField(accessrequest.FieldScreenshotURL, field.TypeString, value)
	}
	if _u.mutation.ScreenshotURLCleared() {
		_spec.ClearField(accessrequest.FieldScreenshotURL, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewComment(); ok {
		_spec.SetField(accessrequest.FieldReviewComment, field.TypeString, value)
	}
	if _u.mutation.ReviewCommentCleared() {
		_spec.ClearField(accessrequest.FieldReviewComment, field.TypeString)
	}
	if value, ok := _u.mutation.ManagerEmail(); ok {
		_spec.SetField(accessrequest.FieldManagerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accessrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(accessrequest.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(accessrequest.FieldResolvedAt, field.TypeTime)
	}
	if _u.mutation.RequesterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.RequesterTable,
			Columns: []string{accessrequest.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequesterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.RequesterTable,
			Columns: []string{accessrequest.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ManagerTable,
			Columns: []string{accessrequest.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ManagerTable,
			Columns: []string{accessrequest.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ReviewerTable,
			Columns: []string{accessrequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ReviewerTable,
			Columns: []string{accessrequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessrequest.AuditLogsTable,
			Columns: []string{accessrequest.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditLogsIDs(); len(nodes) > 0 && !_u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessrequest.AuditLogsTable,
			Columns: []string{accessrequest.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessrequest.AuditLogsTable,
			Columns: []string{accessrequest.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessRequestUpdateOne is the builder for updating a single AccessRequest entity.
type AccessRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessRequestMutation
}

// SetRequesterID sets the "requester_id" field.
func (_u *AccessRequestUpdateOne) SetRequesterID(v int) *AccessRequestUpdateOne {
	_u.mutation.SetRequesterID(v)
	return _u
}

// SetNillableRequesterID sets the "requester_id" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableRequesterID(v *int) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetRequesterID(*v)
	}
	return _u
}

// SetManagerID sets the "manager_id" field.
func (_u *AccessRequestUpdateOne) SetManagerID(v int) *AccessRequestUpdateOne {
	_u.mutation.SetManagerID(v)
	return _u
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableManagerID(v *int) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetManagerID(*v)
	}
	return _u
}

// ClearManagerID clears the value of the "manager_id" field.
func (_u *AccessRequestUpdateOne) ClearManagerID() *AccessRequestUpdateOne {
	_u.mutation.ClearManagerID()
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *AccessRequestUpdateOne) SetReviewerID(v int) *AccessRequestUpdateOne {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableReviewerID(v *int) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *AccessRequestUpdateOne) ClearReviewerID() *AccessRequestUpdateOne {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetResource sets the "resource" field.
func (_u *AccessRequestUpdateOne) SetResource(v string) *AccessRequestUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableResource(v *string) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *AccessRequestUpdateOne) SetReason(v string) *AccessRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableReason(v *string) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccessRequestUpdateOne) SetStatus(v accessrequest.Status) *AccessRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableStatus(v *accessrequest.Status) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScreenshotURL sets the "screenshot_url" field.
func (_u *AccessRequestUpdateOne) SetScreenshotURL(v string) *AccessRequestUpdateOne {
	_u.mutation.SetScreenshotURL(v)
	return _u
}

// SetNillableScreenshotURL sets the "screenshot_url" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableScreenshotURL(v *string) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetScreenshotURL(*v)
	}
	return _u
}

// ClearScreenshotURL clears the value of the "screenshot_url" field.
func (_u *AccessRequestUpdateOne) ClearScreenshotURL() *AccessRequestUpdateOne {
	_u.mutation.ClearScreenshotURL()
	return _u
}

// SetReviewComment sets the "review_comment" field.
func (_u *AccessRequestUpdateOne) SetReviewComment(v string) *AccessRequestUpdateOne {
	_u.mutation.SetReviewComment(v)
	return _u
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableReviewComment(v *string) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetReviewComment(*v)
	}
	return _u
}

// ClearReviewComment clears the value of the "review_comment" field.
func (_u *AccessRequestUpdateOne) ClearReviewComment() *AccessRequestUpdateOne {
	_u.mutation.ClearReviewComment()
	return _u
}

// SetManagerEmail sets the "manager_email" field.
func (_u *AccessRequestUpdateOne) SetManagerEmail(v string) *AccessRequestUpdateOne {
	_u.mutation.SetManagerEmail(v)
	return _u
}

// SetNillableManagerEmail sets the "manager_email" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableManagerEmail(v *string) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetManagerEmail(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessRequestUpdateOne) SetUpdatedAt(v time.Time) *AccessRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *AccessRequestUpdateOne) SetResolvedAt(v time.Time) *AccessRequestUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *AccessRequestUpdateOne) SetNillableResolvedAt(v *time.Time) *AccessRequestUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *AccessRequestUpdateOne) ClearResolvedAt() *AccessRequestUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetRequester sets the "requester" edge to the User entity.
func (_u *AccessRequestUpdateOne) SetRequester(v *User) *AccessRequestUpdateOne {
	return _u.SetRequesterID(v.ID)
}

// SetManager sets the "manager" edge to the User entity.
func (_u *AccessRequestUpdateOne) SetManager(v *User) *AccessRequestUpdateOne {
	return _u.SetManagerID(v.ID)
}

// SetReviewer sets the "reviewer" edge to the User entity.
func (_u *AccessRequestUpdateOne) SetReviewer(v *User) *AccessRequestUpdateOne {
	return _u.SetReviewerID(v.ID)
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_u *AccessRequestUpdateOne) AddAuditLogIDs(ids ...int) *AccessRequestUpdateOne {
	_u.mutation.AddAuditLogIDs(ids...)
	return _u
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_u *AccessRequestUpdateOne) AddAuditLogs(v ...*AuditLog) *AccessRequestUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditLogIDs(ids...)
}

// Mutation returns the AccessRequestMutation object of the builder.
func (_u *AccessRequestUpdateOne) Mutation() *AccessRequestMutation {
	return _u.mutation
}

// ClearRequester clears the "requester" edge to the User entity.
func (_u *AccessRequestUpdateOne) ClearRequester() *AccessRequestUpdateOne {
	_u.mutation.ClearRequester()
	return _u
}

// ClearManager clears the "manager" edge to the User entity.
func (_u *AccessRequestUpdateOne) ClearManager() *AccessRequestUpdateOne {
	_u.mutation.ClearManager()
	return _u
}

// ClearReviewer clears the "reviewer" edge to the User entity.
func (_u *AccessRequestUpdateOne) ClearReviewer() *AccessRequestUpdateOne {
	_u.mutation.ClearReviewer()
	return _u
}

// ClearAuditLogs clears all "audit_logs" edges to the AuditLog entity.
func (_u *AccessRequestUpdateOne) ClearAuditLogs() *AccessRequestUpdateOne {
	_u.mutation.ClearAuditLogs()
	return _u
}

// RemoveAuditLogIDs removes the "audit_logs" edge to AuditLog entities by IDs.
func (_u *AccessRequestUpdateOne) RemoveAuditLogIDs(ids ...int) *AccessRequestUpdateOne {
	_u.mutation.RemoveAuditLogIDs(ids...)
	return _u
}

// RemoveAuditLogs removes "audit_logs" edges to AuditLog entities.
func (_u *AccessRequestUpdateOne) RemoveAuditLogs(v ...*AuditLog) *AccessRequestUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditLogIDs(ids...)
}

// Where appends a list predicates to the AccessRequestUpdate builder.
func (_u *AccessRequestUpdateOne) Where(ps ...predicate.AccessRequest) *AccessRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessRequestUpdateOne) Select(field string, fields ...string) *AccessRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessRequest entity.
func (_u *AccessRequestUpdateOne) Save(ctx context.Context) (*AccessRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessRequestUpdateOne) SaveX(ctx context.Context) *AccessRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accessrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := accessrequest.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := accessrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accessrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagerEmail(); ok {
		if err := accessrequest.ManagerEmailValidator(v); err != nil {
			return &ValidationError{Name: "manager_email", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.manager_email": %w`, err)}
		}
	}
	if _u.mutation.RequesterCleared() && len(_u.mutation.RequesterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccessRequest.requester"`)
	}
	return nil
}

func (_u *AccessRequestUpdateOne) sqlSave(ctx context.Context) (_node *AccessRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessrequest.Table, accessrequest.Columns, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessrequest.FieldID)
		for _, f := range fields {
			if !accessrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accessrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(accessrequest.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(accessrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accessrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScreenshotURL(); ok {
		_spec.SetField(accessrequest.FieldScreenshotURL, field.TypeString, value)
	}
	if _u.mutation.ScreenshotURLCleared() {
		_spec.ClearField(accessrequest.FieldScreenshotURL, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewComment(); ok {
		_spec.SetField(accessrequest.FieldReviewComment, field.TypeString, value)
	}
	if _u.mutation.ReviewCommentCleared() {
		_spec.ClearField(accessrequest.FieldReviewComment, field.TypeString)
	}
	if value, ok := _u.mutation.ManagerEmail(); ok {
		_spec.SetField(accessrequest.FieldManagerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accessrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(accessrequest.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(accessrequest.FieldResolvedAt, field.TypeTime)
	}
	if _u.mutation.RequesterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.RequesterTable,
			Columns: []string{accessrequest.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequesterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.RequesterTable,
			Columns: []string{accessrequest.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ManagerTable,
			Columns: []string{accessrequest.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ManagerTable,
			Columns: []string{accessrequest.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ReviewerTable,
			Columns: []string{accessrequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessrequest.ReviewerTable,
			Columns: []string{accessrequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessrequest.AuditLogsTable,
			Columns: []string{accessrequest.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditLogsIDs(); len(nodes) > 0 && !_u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessrequest.AuditLogsTable,
			Columns: []string{accessrequest.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accessrequest.AuditLogsTable,
			Columns: []string{accessrequest.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccessRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
