// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/auditlog"
	"cerberus/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccessRequestID sets the "access_request_id" field.
func (_u *AuditLogUpdate) SetAccessRequestID(v int) *AuditLogUpdate {
	_u.mutation.SetAccessRequestID(v)
	return _u
}

// SetNillableAccessRequestID sets the "access_request_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAccessRequestID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetAccessRequestID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v auditlog.Action) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *auditlog.Action) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetActorEmail sets the "actor_email" field.
func (_u *AuditLogUpdate) SetActorEmail(v string) *AuditLogUpdate {
	_u.mutation.SetActorEmail(v)
	return _u
}

// SetNillableActorEmail sets the "actor_email" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorEmail(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorEmail(*v)
	}
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *AuditLogUpdate) SetActorRole(v string) *AuditLogUpdate {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorRole(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuditLogUpdate) SetMetadata(v string) *AuditLogUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableMetadata(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AuditLogUpdate) ClearMetadata() *AuditLogUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetAccessRequest sets the "access_request" edge to the AccessRequest entity.
func (_u *AuditLogUpdate) SetAccessRequest(v *AccessRequest) *AuditLogUpdate {
	return _u.SetAccessRequestID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearAccessRequest clears the "access_request" edge to the AccessRequest entity.
func (_u *AuditLogUpdate) ClearAccessRequest() *AuditLogUpdate {
	_u.mutation.ClearAccessRequest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorEmail(); ok {
		if err := auditlog.ActorEmailValidator(v); err != nil {
			return &ValidationError{Name: "actor_email", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorRole(); ok {
		if err := auditlog.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_role": %w`, err)}
		}
	}
	if _u.mutation.AccessRequestCleared() && len(_u.mutation.AccessRequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditLog.access_request"`)
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ActorEmail(); ok {
		_spec.SetField(auditlog.FieldActorEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(auditlog.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(auditlog.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(auditlog.FieldMetadata, field.TypeString)
	}
	if _u.mutation.AccessRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.AccessRequestTable,
			Columns: []string{auditlog.AccessRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.AccessRequestTable,
			Columns: []string{auditlog.AccessRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetAccessRequestID sets the "access_request_id" field.
func (_u *AuditLogUpdateOne) SetAccessRequestID(v int) *AuditLogUpdateOne {
	_u.mutation.SetAccessRequestID(v)
	return _u
}

// SetNillableAccessRequestID sets the "access_request_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAccessRequestID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAccessRequestID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v auditlog.Action) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *auditlog.Action) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetActorEmail sets the "actor_email" field.
func (_u *AuditLogUpdateOne) SetActorEmail(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorEmail(v)
	return _u
}

// SetNillableActorEmail sets the "actor_email" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorEmail(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorEmail(*v)
	}
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *AuditLogUpdateOne) SetActorRole(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorRole(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuditLogUpdateOne) SetMetadata(v string) *AuditLogUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableMetadata(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AuditLogUpdateOne) ClearMetadata() *AuditLogUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetAccessRequest sets the "access_request" edge to the AccessRequest entity.
func (_u *AuditLogUpdateOne) SetAccessRequest(v *AccessRequest) *AuditLogUpdateOne {
	return _u.SetAccessRequestID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearAccessRequest clears the "access_request" edge to the AccessRequest entity.
func (_u *AuditLogUpdateOne) ClearAccessRequest() *AuditLogUpdateOne {
	_u.mutation.ClearAccessRequest()
	return _u
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorEmail(); ok {
		if err := auditlog.ActorEmailValidator(v); err != nil {
			return &ValidationError{Name: "actor_email", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorRole(); ok {
		if err := auditlog.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_role": %w`, err)}
		}
	}
	if _u.mutation.AccessRequestCleared() && len(_u.mutation.AccessRequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditLog.access_request"`)
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ActorEmail(); ok {
		_spec.SetField(auditlog.FieldActorEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(auditlog.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(auditlog.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(auditlog.FieldMetadata, field.TypeString)
	}
	if _u.mutation.AccessRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.AccessRequestTable,
			Columns: []string{auditlog.AccessRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.AccessRequestTable,
			Columns: []string{auditlog.AccessRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
