// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/auditlog"
	"cerberus/ent/predicate"
	"cerberus/ent/user"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAccessRequest = "AccessRequest"
	TypeAuditLog      = "AuditLog"
	TypeUser          = "User"
)

// AccessRequestMutation represents an operation that mutates the AccessRequest nodes in the graph.
type AccessRequestMutation struct {
	config
	op                Op
	typ               string
	id                *int
	resource          *string
	reason            *string
	status            *accessrequest.Status
	screenshot_url    *string
	review_comment    *string
	manager_email     *string
	created_at        *time.Time
	updated_at        *time.Time
	resolved_at       *time.Time
	clearedFields     map[string]struct{}
	requester         *int
	clearedrequester  bool
	manager           *int
	clearedmanager    bool
	reviewer          *int
	clearedreviewer   bool
	audit_logs        map[int]struct{}
	removedaudit_logs map[int]struct{}
	clearedaudit_logs bool
	done              bool
	oldValue          func(context.Context) (*AccessRequest, error)
	predicates        []predicate.AccessRequest
}

var _ ent.Mutation = (*AccessRequestMutation)(nil)

// accessrequestOption allows management of the mutation configuration using functional options.
type accessrequestOption func(*AccessRequestMutation)

// newAccessRequestMutation creates new mutation for the AccessRequest entity.
func newAccessRequestMutation(c config, op Op, opts ...accessrequestOption) *AccessRequestMutation {
	m := &AccessRequestMutation{
		config:        c,
		op:            op,
		typ:           TypeAccessRequest,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAccessRequestID sets the ID field of the mutation.
func withAccessRequestID(id int) accessrequestOption {
	return func(m *AccessRequestMutation) {
		var (
			err   error
			once  sync.Once
			value *AccessRequest
		)
		m.oldValue = func(ctx context.Context) (*AccessRequest, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AccessRequest.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAccessRequest sets the old AccessRequest of the mutation.
func withAccessRequest(node *AccessRequest) accessrequestOption {
	return func(m *AccessRequestMutation) {
		m.oldValue = func(context.Context) (*AccessRequest, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AccessRequestMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AccessRequestMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AccessRequestMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AccessRequestMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AccessRequest.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRequesterID sets the "requester_id" field.
func (m *AccessRequestMutation) SetRequesterID(i int) {
	m.requester = &i
}

// RequesterID returns the value of the "requester_id" field in the mutation.
func (m *AccessRequestMutation) RequesterID() (r int, exists bool) {
	v := m.requester
	if v == nil {
		return
	}
	return *v, true
}

// OldRequesterID returns the old "requester_id" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldRequesterID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequesterID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequesterID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequesterID: %w", err)
	}
	return oldValue.RequesterID, nil
}

// ResetRequesterID resets all changes to the "requester_id" field.
func (m *AccessRequestMutation) ResetRequesterID() {
	m.requester = nil
}

// SetManagerID sets the "manager_id" field.
func (m *AccessRequestMutation) SetManagerID(i int) {
	m.manager = &i
}

// ManagerID returns the value of the "manager_id" field in the mutation.
func (m *AccessRequestMutation) ManagerID() (r int, exists bool) {
	v := m.manager
	if v == nil {
		return
	}
	return *v, true
}

// OldManagerID returns the old "manager_id" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldManagerID(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldManagerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldManagerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldManagerID: %w", err)
	}
	return oldValue.ManagerID, nil
}

// ClearManagerID clears the value of the "manager_id" field.
func (m *AccessRequestMutation) ClearManagerID() {
	m.manager = nil
	m.clearedFields[accessrequest.FieldManagerID] = struct{}{}
}

// ManagerIDCleared returns if the "manager_id" field was cleared in this mutation.
func (m *AccessRequestMutation) ManagerIDCleared() bool {
	_, ok := m.clearedFields[accessrequest.FieldManagerID]
	return ok
}

// ResetManagerID resets all changes to the "manager_id" field.
func (m *AccessRequestMutation) ResetManagerID() {
	m.manager = nil
	delete(m.clearedFields, accessrequest.FieldManagerID)
}

// SetReviewerID sets the "reviewer_id" field.
func (m *AccessRequestMutation) SetReviewerID(i int) {
	m.reviewer = &i
}

// ReviewerID returns the value of the "reviewer_id" field in the mutation.
func (m *AccessRequestMutation) ReviewerID() (r int, exists bool) {
	v := m.reviewer
	if v == nil {
		return
	}
	return *v, true
}

// OldReviewerID returns the old "reviewer_id" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldReviewerID(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReviewerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReviewerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReviewerID: %w", err)
	}
	return oldValue.ReviewerID, nil
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (m *AccessRequestMutation) ClearReviewerID() {
	m.reviewer = nil
	m.clearedFields[accessrequest.FieldReviewerID] = struct{}{}
}

// ReviewerIDCleared returns if the "reviewer_id" field was cleared in this mutation.
func (m *AccessRequestMutation) ReviewerIDCleared() bool {
	_, ok := m.clearedFields[accessrequest.FieldReviewerID]
	return ok
}

// ResetReviewerID resets all changes to the "reviewer_id" field.
func (m *AccessRequestMutation) ResetReviewerID() {
	m.reviewer = nil
	delete(m.clearedFields, accessrequest.FieldReviewerID)
}

// SetResource sets the "resource" field.
func (m *AccessRequestMutation) SetResource(s string) {
	m.resource = &s
}

// Resource returns the value of the "resource" field in the mutation.
func (m *AccessRequestMutation) Resource() (r string, exists bool) {
	v := m.resource
	if v == nil {
		return
	}
	return *v, true
}

// OldResource returns the old "resource" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldResource(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResource is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResource requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResource: %w", err)
	}
	return oldValue.Resource, nil
}

// ResetResource resets all changes to the "resource" field.
func (m *AccessRequestMutation) ResetResource() {
	m.resource = nil
}

// SetReason sets the "reason" field.
func (m *AccessRequestMutation) SetReason(s string) {
	m.reason = &s
}

// Reason returns the value of the "reason" field in the mutation.
func (m *AccessRequestMutation) Reason() (r string, exists bool) {
	v := m.reason
	if v == nil {
		return
	}
	return *v, true
}

// OldReason returns the old "reason" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReason: %w", err)
	}
	return oldValue.Reason, nil
}

// ResetReason resets all changes to the "reason" field.
func (m *AccessRequestMutation) ResetReason() {
	m.reason = nil
}

// SetStatus sets the "status" field.
func (m *AccessRequestMutation) SetStatus(a accessrequest.Status) {
	m.status = &a
}

// Status returns the value of the "status" field in the mutation.
func (m *AccessRequestMutation) Status() (r accessrequest.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldStatus(ctx context.Context) (v accessrequest.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *AccessRequestMutation) ResetStatus() {
	m.status = nil
}

// SetScreenshotURL sets the "screenshot_url" field.
func (m *AccessRequestMutation) SetScreenshotURL(s string) {
	m.screenshot_url = &s
}

// ScreenshotURL returns the value of the "screenshot_url" field in the mutation.
func (m *AccessRequestMutation) ScreenshotURL() (r string, exists bool) {
	v := m.screenshot_url
	if v == nil {
		return
	}
	return *v, true
}

// OldScreenshotURL returns the old "screenshot_url" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldScreenshotURL(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScreenshotURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScreenshotURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScreenshotURL: %w", err)
	}
	return oldValue.ScreenshotURL, nil
}

// ClearScreenshotURL clears the value of the "screenshot_url" field.
func (m *AccessRequestMutation) ClearScreenshotURL() {
	m.screenshot_url = nil
	m.clearedFields[accessrequest.FieldScreenshotURL] = struct{}{}
}

// ScreenshotURLCleared returns if the "screenshot_url" field was cleared in this mutation.
func (m *AccessRequestMutation) ScreenshotURLCleared() bool {
	_, ok := m.clearedFields[accessrequest.FieldScreenshotURL]
	return ok
}

// ResetScreenshotURL resets all changes to the "screenshot_url" field.
func (m *AccessRequestMutation) ResetScreenshotURL() {
	m.screenshot_url = nil
	delete(m.clearedFields, accessrequest.FieldScreenshotURL)
}

// SetReviewComment sets the "review_comment" field.
func (m *AccessRequestMutation) SetReviewComment(s string) {
	m.review_comment = &s
}

// ReviewComment returns the value of the "review_comment" field in the mutation.
func (m *AccessRequestMutation) ReviewComment() (r string, exists bool) {
	v := m.review_comment
	if v == nil {
		return
	}
	return *v, true
}

// OldReviewComment returns the old "review_comment" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldReviewComment(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReviewComment is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReviewComment requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReviewComment: %w", err)
	}
	return oldValue.ReviewComment, nil
}

// ClearReviewComment clears the value of the "review_comment" field.
func (m *AccessRequestMutation) ClearReviewComment() {
	m.review_comment = nil
	m.clearedFields[accessrequest.FieldReviewComment] = struct{}{}
}

// ReviewCommentCleared returns if the "review_comment" field was cleared in this mutation.
func (m *AccessRequestMutation) ReviewCommentCleared() bool {
	_, ok := m.clearedFields[accessrequest.FieldReviewComment]
	return ok
}

// ResetReviewComment resets all changes to the "review_comment" field.
func (m *AccessRequestMutation) ResetReviewComment() {
	m.review_comment = nil
	delete(m.clearedFields, accessrequest.FieldReviewComment)
}

// SetManagerEmail sets the "manager_email" field.
func (m *AccessRequestMutation) SetManagerEmail(s string) {
	m.manager_email = &s
}

// ManagerEmail returns the value of the "manager_email" field in the mutation.
func (m *AccessRequestMutation) ManagerEmail() (r string, exists bool) {
	v := m.manager_email
	if v == nil {
		return
	}
	return *v, true
}

// OldManagerEmail returns the old "manager_email" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldManagerEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldManagerEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldManagerEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldManagerEmail: %w", err)
	}
	return oldValue.ManagerEmail, nil
}

// ResetManagerEmail resets all changes to the "manager_email" field.
func (m *AccessRequestMutation) ResetManagerEmail() {
	m.manager_email = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AccessRequestMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AccessRequestMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AccessRequestMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AccessRequestMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AccessRequestMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AccessRequestMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetResolvedAt sets the "resolved_at" field.
func (m *AccessRequestMutation) SetResolvedAt(t time.Time) {
	m.resolved_at = &t
}

// ResolvedAt returns the value of the "resolved_at" field in the mutation.
func (m *AccessRequestMutation) ResolvedAt() (r time.Time, exists bool) {
	v := m.resolved_at
	if v == nil {
		return
	}
	return *v, true
}

// OldResolvedAt returns the old "resolved_at" field's value of the AccessRequest entity.
// If the AccessRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccessRequestMutation) OldResolvedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResolvedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResolvedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResolvedAt: %w", err)
	}
	return oldValue.ResolvedAt, nil
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (m *AccessRequestMutation) ClearResolvedAt() {
	m.resolved_at = nil
	m.clearedFields[accessrequest.FieldResolvedAt] = struct{}{}
}

// ResolvedAtCleared returns if the "resolved_at" field was cleared in this mutation.
func (m *AccessRequestMutation) ResolvedAtCleared() bool {
	_, ok := m.clearedFields[accessrequest.FieldResolvedAt]
	return ok
}

// ResetResolvedAt resets all changes to the "resolved_at" field.
func (m *AccessRequestMutation) ResetResolvedAt() {
	m.resolved_at = nil
	delete(m.clearedFields, accessrequest.FieldResolvedAt)
}

// ClearRequester clears the "requester" edge to the User entity.
func (m *AccessRequestMutation) ClearRequester() {
	m.clearedrequester = true
	m.clearedFields[accessrequest.FieldRequesterID] = struct{}{}
}

// RequesterCleared reports if the "requester" edge to the User entity was cleared.
func (m *AccessRequestMutation) RequesterCleared() bool {
	return m.clearedrequester
}

// RequesterIDs returns the "requester" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// RequesterID instead. It exists only for internal usage by the builders.
func (m *AccessRequestMutation) RequesterIDs() (ids []int) {
	if id := m.requester; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRequester resets all changes to the "requester" edge.
func (m *AccessRequestMutation) ResetRequester() {
	m.requester = nil
	m.clearedrequester = false
}

// ClearManager clears the "manager" edge to the User entity.
func (m *AccessRequestMutation) ClearManager() {
	m.clearedmanager = true
	m.clearedFields[accessrequest.FieldManagerID] = struct{}{}
}

// ManagerCleared reports if the "manager" edge to the User entity was cleared.
func (m *AccessRequestMutation) ManagerCleared() bool {
	return m.ManagerIDCleared() || m.clearedmanager
}

// ManagerIDs returns the "manager" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ManagerID instead. It exists only for internal usage by the builders.
func (m *AccessRequestMutation) ManagerIDs() (ids []int) {
	if id := m.manager; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetManager resets all changes to the "manager" edge.
func (m *AccessRequestMutation) ResetManager() {
	m.manager = nil
	m.clearedmanager = false
}

// ClearReviewer clears the "reviewer" edge to the User entity.
func (m *AccessRequestMutation) ClearReviewer() {
	m.clearedreviewer = true
	m.clearedFields[accessrequest.FieldReviewerID] = struct{}{}
}

// ReviewerCleared reports if the "reviewer" edge to the User entity was cleared.
func (m *AccessRequestMutation) ReviewerCleared() bool {
	return m.ReviewerIDCleared() || m.clearedreviewer
}

// ReviewerIDs returns the "reviewer" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ReviewerID instead. It exists only for internal usage by the builders.
func (m *AccessRequestMutation) ReviewerIDs() (ids []int) {
	if id := m.reviewer; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetReviewer resets all changes to the "reviewer" edge.
func (m *AccessRequestMutation) ResetReviewer() {
	m.reviewer = nil
	m.clearedreviewer = false
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by ids.
func (m *AccessRequestMutation) AddAuditLogIDs(ids ...int) {
	if m.audit_logs == nil {
		m.audit_logs = make(map[int]struct{})
	}
	for i := range ids {
		m.audit_logs[ids[i]] = struct{}{}
	}
}

// ClearAuditLogs clears the "audit_logs" edge to the AuditLog entity.
func (m *AccessRequestMutation) ClearAuditLogs() {
	m.clearedaudit_logs = true
}

// AuditLogsCleared reports if the "audit_logs" edge to the AuditLog entity was cleared.
func (m *AccessRequestMutation) AuditLogsCleared() bool {
	return m.clearedaudit_logs
}

// RemoveAuditLogIDs removes the "audit_logs" edge to the AuditLog entity by IDs.
func (m *AccessRequestMutation) RemoveAuditLogIDs(ids ...int) {
	if m.removedaudit_logs == nil {
		m.removedaudit_logs = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.audit_logs, ids[i])
		m.removedaudit_logs[ids[i]] = struct{}{}
	}
}

// RemovedAuditLogs returns the removed IDs of the "audit_logs" edge to the AuditLog entity.
func (m *AccessRequestMutation) RemovedAuditLogsIDs() (ids []int) {
	for id := range m.removedaudit_logs {
		ids = append(ids, id)
	}
	return
}

// AuditLogsIDs returns the "audit_logs" edge IDs in the mutation.
func (m *AccessRequestMutation) AuditLogsIDs() (ids []int) {
	for id := range m.audit_logs {
		ids = append(ids, id)
	}
	return
}

// ResetAuditLogs resets all changes to the "audit_logs" edge.
func (m *AccessRequestMutation) ResetAuditLogs() {
	m.audit_logs = nil
	m.clearedaudit_logs = false
	m.removedaudit_logs = nil
}

// Where appends a list predicates to the AccessRequestMutation builder.
func (m *AccessRequestMutation) Where(ps ...predicate.AccessRequest) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AccessRequestMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AccessRequestMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AccessRequest, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AccessRequestMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AccessRequestMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AccessRequest).
func (m *AccessRequestMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AccessRequestMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.requester != nil {
		fields = append(fields, accessrequest.FieldRequesterID)
	}
	if m.manager != nil {
		fields = append(fields, accessrequest.FieldManagerID)
	}
	if m.reviewer != nil {
		fields = append(fields, accessrequest.FieldReviewerID)
	}
	if m.resource != nil {
		fields = append(fields, accessrequest.FieldResource)
	}
	if m.reason != nil {
		fields = append(fields, accessrequest.FieldReason)
	}
	if m.status != nil {
		fields = append(fields, accessrequest.FieldStatus)
	}
	if m.screenshot_url != nil {
		fields = append(fields, accessrequest.FieldScreenshotURL)
	}
	if m.review_comment != nil {
		fields = append(fields, accessrequest.FieldReviewComment)
	}
	if m.manager_email != nil {
		fields = append(fields, accessrequest.FieldManagerEmail)
	}
	if m.created_at != nil {
		fields = append(fields, accessrequest.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, accessrequest.FieldUpdatedAt)
	}
	if m.resolved_at != nil {
		fields = append(fields, accessrequest.FieldResolvedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AccessRequestMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case accessrequest.FieldRequesterID:
		return m.RequesterID()
	case accessrequest.FieldManagerID:
		return m.ManagerID()
	case accessrequest.FieldReviewerID:
		return m.ReviewerID()
	case accessrequest.FieldResource:
		return m.Resource()
	case accessrequest.FieldReason:
		return m.Reason()
	case accessrequest.FieldStatus:
		return m.Status()
	case accessrequest.FieldScreenshotURL:
		return m.ScreenshotURL()
	case accessrequest.FieldReviewComment:
		return m.ReviewComment()
	case accessrequest.FieldManagerEmail:
		return m.ManagerEmail()
	case accessrequest.FieldCreatedAt:
		return m.CreatedAt()
	case accessrequest.FieldUpdatedAt:
		return m.UpdatedAt()
	case accessrequest.FieldResolvedAt:
		return m.ResolvedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AccessRequestMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case accessrequest.FieldRequesterID:
		return m.OldRequesterID(ctx)
	case accessrequest.FieldManagerID:
		return m.OldManagerID(ctx)
	case accessrequest.FieldReviewerID:
		return m.OldReviewerID(ctx)
	case accessrequest.FieldResource:
		return m.OldResource(ctx)
	case accessrequest.FieldReason:
		return m.OldReason(ctx)
	case accessrequest.FieldStatus:
		return m.OldStatus(ctx)
	case accessrequest.FieldScreenshotURL:
		return m.OldScreenshotURL(ctx)
	case accessrequest.FieldReviewComment:
		return m.OldReviewComment(ctx)
	case accessrequest.FieldManagerEmail:
		return m.OldManagerEmail(ctx)
	case accessrequest.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case accessrequest.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case accessrequest.FieldResolvedAt:
		return m.OldResolvedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AccessRequest field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccessRequestMutation) SetField(name string, value ent.Value) error {
	switch name {
	case accessrequest.FieldRequesterID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequesterID(v)
		return nil
	case accessrequest.FieldManagerID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManagerID(v)
		return nil
	case accessrequest.FieldReviewerID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReviewerID(v)
		return nil
	case accessrequest.FieldResource:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResource(v)
		return nil
	case accessrequest.FieldReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReason(v)
		return nil
	case accessrequest.FieldStatus:
		v, ok := value.(accessrequest.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case accessrequest.FieldScreenshotURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScreenshotURL(v)
		return nil
	case accessrequest.FieldReviewComment:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReviewComment(v)
		return nil
	case accessrequest.FieldManagerEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManagerEmail(v)
		return nil
	case accessrequest.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case accessrequest.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case accessrequest.FieldResolvedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResolvedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AccessRequest field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AccessRequestMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AccessRequestMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccessRequestMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AccessRequest numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AccessRequestMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(accessrequest.FieldManagerID) {
		fields = append(fields, accessrequest.FieldManagerID)
	}
	if m.FieldCleared(accessrequest.FieldReviewerID) {
		fields = append(fields, accessrequest.FieldReviewerID)
	}
	if m.FieldCleared(accessrequest.FieldScreenshotURL) {
		fields = append(fields, accessrequest.FieldScreenshotURL)
	}
	if m.FieldCleared(accessrequest.FieldReviewComment) {
		fields = append(fields, accessrequest.FieldReviewComment)
	}
	if m.FieldCleared(accessrequest.FieldResolvedAt) {
		fields = append(fields, accessrequest.FieldResolvedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AccessRequestMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AccessRequestMutation) ClearField(name string) error {
	switch name {
	case accessrequest.FieldManagerID:
		m.ClearManagerID()
		return nil
	case accessrequest.FieldReviewerID:
		m.ClearReviewerID()
		return nil
	case accessrequest.FieldScreenshotURL:
		m.ClearScreenshotURL()
		return nil
	case accessrequest.FieldReviewComment:
		m.ClearReviewComment()
		return nil
	case accessrequest.FieldResolvedAt:
		m.ClearResolvedAt()
		return nil
	}
	return fmt.Errorf("unknown AccessRequest nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AccessRequestMutation) ResetField(name string) error {
	switch name {
	case accessrequest.FieldRequesterID:
		m.ResetRequesterID()
		return nil
	case accessrequest.FieldManagerID:
		m.ResetManagerID()
		return nil
	case accessrequest.FieldReviewerID:
		m.ResetReviewerID()
		return nil
	case accessrequest.FieldResource:
		m.ResetResource()
		return nil
	case accessrequest.FieldReason:
		m.ResetReason()
		return nil
	case accessrequest.FieldStatus:
		m.ResetStatus()
		return nil
	case accessrequest.FieldScreenshotURL:
		m.ResetScreenshotURL()
		return nil
	case accessrequest.FieldReviewComment:
		m.ResetReviewComment()
		return nil
	case accessrequest.FieldManagerEmail:
		m.ResetManagerEmail()
		return nil
	case accessrequest.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case accessrequest.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case accessrequest.FieldResolvedAt:
		m.ResetResolvedAt()
		return nil
	}
	return fmt.Errorf("unknown AccessRequest field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AccessRequestMutation) AddedEdges() []string {
	edges := make([]string, 0, 4)
	if m.requester != nil {
		edges = append(edges, accessrequest.EdgeRequester)
	}
	if m.manager != nil {
		edges = append(edges, accessrequest.EdgeManager)
	}
	if m.reviewer != nil {
		edges = append(edges, accessrequest.EdgeReviewer)
	}
	if m.audit_logs != nil {
		edges = append(edges, accessrequest.EdgeAuditLogs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AccessRequestMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case accessrequest.EdgeRequester:
		if id := m.requester; id != nil {
			return []ent.Value{*id}
		}
	case accessrequest.EdgeManager:
		if id := m.manager; id != nil {
			return []ent.Value{*id}
		}
	case accessrequest.EdgeReviewer:
		if id := m.reviewer; id != nil {
			return []ent.Value{*id}
		}
	case accessrequest.EdgeAuditLogs:
		ids := make([]ent.Value, 0, len(m.audit_logs))
		for id := range m.audit_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AccessRequestMutation) RemovedEdges() []string {
	edges := make([]string, 0, 4)
	if m.removedaudit_logs != nil {
		edges = append(edges, accessrequest.EdgeAuditLogs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AccessRequestMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case accessrequest.EdgeAuditLogs:
		ids := make([]ent.Value, 0, len(m.removedaudit_logs))
		for id := range m.removedaudit_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AccessRequestMutation) ClearedEdges() []string {
	edges := make([]string, 0, 4)
	if m.clearedrequester {
		edges = append(edges, accessrequest.EdgeRequester)
	}
	if m.clearedmanager {
		edges = append(edges, accessrequest.EdgeManager)
	}
	if m.clearedreviewer {
		edges = append(edges, accessrequest.EdgeReviewer)
	}
	if m.clearedaudit_logs {
		edges = append(edges, accessrequest.EdgeAuditLogs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AccessRequestMutation) EdgeCleared(name string) bool {
	switch name {
	case accessrequest.EdgeRequester:
		return m.clearedrequester
	case accessrequest.EdgeManager:
		return m.clearedmanager
	case accessrequest.EdgeReviewer:
		return m.clearedreviewer
	case accessrequest.EdgeAuditLogs:
		return m.clearedaudit_logs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AccessRequestMutation) ClearEdge(name string) error {
	switch name {
	case accessrequest.EdgeRequester:
		m.ClearRequester()
		return nil
	case accessrequest.EdgeManager:
		m.ClearManager()
		return nil
	case accessrequest.EdgeReviewer:
		m.ClearReviewer()
		return nil
	}
	return fmt.Errorf("unknown AccessRequest unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AccessRequestMutation) ResetEdge(name string) error {
	switch name {
	case accessrequest.EdgeRequester:
		m.ResetRequester()
		return nil
	case accessrequest.EdgeManager:
		m.ResetManager()
		return nil
	case accessrequest.EdgeReviewer:
		m.ResetReviewer()
		return nil
	case accessrequest.EdgeAuditLogs:
		m.ResetAuditLogs()
		return nil
	}
	return fmt.Errorf("unknown AccessRequest edge %s", name)
}

// AuditLogMutation represents an operation that mutates the AuditLog nodes in the graph.
type AuditLogMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int
	action                *auditlog.Action
	actor_email           *string
	actor_role            *string
	metadata              *string
	created_at            *time.Time
	clearedFields         map[string]struct{}
	access_request        *int
	clearedaccess_request bool
	done                  bool
	oldValue              func(context.Context) (*AuditLog, error)
	predicates            []predicate.AuditLog
}

var _ ent.Mutation = (*AuditLogMutation)(nil)

// auditlogOption allows management of the mutation configuration using functional options.
type auditlogOption func(*AuditLogMutation)

// newAuditLogMutation creates new mutation for the AuditLog entity.
func newAuditLogMutation(c config, op Op, opts ...auditlogOption) *AuditLogMutation {
	m := &AuditLogMutation{
		config:        c,
		op:            op,
		typ:           TypeAuditLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAuditLogID sets the ID field of the mutation.
func withAuditLogID(id int) auditlogOption {
	return func(m *AuditLogMutation) {
		var (
			err   error
			once  sync.Once
			value *AuditLog
		)
		m.oldValue = func(ctx context.Context) (*AuditLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AuditLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAuditLog sets the old AuditLog of the mutation.
func withAuditLog(node *AuditLog) auditlogOption {
	return func(m *AuditLogMutation) {
		m.oldValue = func(context.Context) (*AuditLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AuditLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AuditLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AuditLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AuditLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AuditLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAccessRequestID sets the "access_request_id" field.
func (m *AuditLogMutation) SetAccessRequestID(i int) {
	m.access_request = &i
}

// AccessRequestID returns the value of the "access_request_id" field in the mutation.
func (m *AuditLogMutation) AccessRequestID() (r int, exists bool) {
	v := m.access_request
	if v == nil {
		return
	}
	return *v, true
}

// OldAccessRequestID returns the old "access_request_id" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldAccessRequestID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccessRequestID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccessRequestID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccessRequestID: %w", err)
	}
	return oldValue.AccessRequestID, nil
}

// ResetAccessRequestID resets all changes to the "access_request_id" field.
func (m *AuditLogMutation) ResetAccessRequestID() {
	m.access_request = nil
}

// SetAction sets the "action" field.
func (m *AuditLogMutation) SetAction(a auditlog.Action) {
	m.action = &a
}

// Action returns the value of the "action" field in the mutation.
func (m *AuditLogMutation) Action() (r auditlog.Action, exists bool) {
	v := m.action
	if v == nil {
		return
	}
	return *v, true
}

// OldAction returns the old "action" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldAction(ctx context.Context) (v auditlog.Action, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAction is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAction requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAction: %w", err)
	}
	return oldValue.Action, nil
}

// ResetAction resets all changes to the "action" field.
func (m *AuditLogMutation) ResetAction() {
	m.action = nil
}

// SetActorEmail sets the "actor_email" field.
func (m *AuditLogMutation) SetActorEmail(s string) {
	m.actor_email = &s
}

// ActorEmail returns the value of the "actor_email" field in the mutation.
func (m *AuditLogMutation) ActorEmail() (r string, exists bool) {
	v := m.actor_email
	if v == nil {
		return
	}
	return *v, true
}

// OldActorEmail returns the old "actor_email" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldActorEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActorEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActorEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActorEmail: %w", err)
	}
	return oldValue.ActorEmail, nil
}

// ResetActorEmail resets all changes to the "actor_email" field.
func (m *AuditLogMutation) ResetActorEmail() {
	m.actor_email = nil
}

// SetActorRole sets the "actor_role" field.
func (m *AuditLogMutation) SetActorRole(s string) {
	m.actor_role = &s
}

// ActorRole returns the value of the "actor_role" field in the mutation.
func (m *AuditLogMutation) ActorRole() (r string, exists bool) {
	v := m.actor_role
	if v == nil {
		return
	}
	return *v, true
}

// OldActorRole returns the old "actor_role" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldActorRole(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActorRole is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActorRole requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActorRole: %w", err)
	}
	return oldValue.ActorRole, nil
}

// ResetActorRole resets all changes to the "actor_role" field.
func (m *AuditLogMutation) ResetActorRole() {
	m.actor_role = nil
}

// SetMetadata sets the "metadata" field.
func (m *AuditLogMutation) SetMetadata(s string) {
	m.metadata = &s
}

// Metadata returns the value of the "metadata" field in the mutation.
func (m *AuditLogMutation) Metadata() (r string, exists bool) {
	v := m.metadata
	if v == nil {
		return
	}
	return *v, true
}

// OldMetadata returns the old "metadata" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldMetadata(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMetadata is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMetadata requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMetadata: %w", err)
	}
	return oldValue.Metadata, nil
}

// ClearMetadata clears the value of the "metadata" field.
func (m *AuditLogMutation) ClearMetadata() {
	m.metadata = nil
	m.clearedFields[auditlog.FieldMetadata] = struct{}{}
}

// MetadataCleared returns if the "metadata" field was cleared in this mutation.
func (m *AuditLogMutation) MetadataCleared() bool {
	_, ok := m.clearedFields[auditlog.FieldMetadata]
	return ok
}

// ResetMetadata resets all changes to the "metadata" field.
func (m *AuditLogMutation) ResetMetadata() {
	m.metadata = nil
	delete(m.clearedFields, auditlog.FieldMetadata)
}

// SetCreatedAt sets the "created_at" field.
func (m *AuditLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AuditLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AuditLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// ClearAccessRequest clears the "access_request" edge to the AccessRequest entity.
func (m *AuditLogMutation) ClearAccessRequest() {
	m.clearedaccess_request = true
	m.clearedFields[auditlog.FieldAccessRequestID] = struct{}{}
}

// AccessRequestCleared reports if the "access_request" edge to the AccessRequest entity was cleared.
func (m *AuditLogMutation) AccessRequestCleared() bool {
	return m.clearedaccess_request
}

// AccessRequestIDs returns the "access_request" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AccessRequestID instead. It exists only for internal usage by the builders.
func (m *AuditLogMutation) AccessRequestIDs() (ids []int) {
	if id := m.access_request; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAccessRequest resets all changes to the "access_request" edge.
func (m *AuditLogMutation) ResetAccessRequest() {
	m.access_request = nil
	m.clearedaccess_request = false
}

// Where appends a list predicates to the AuditLogMutation builder.
func (m *AuditLogMutation) Where(ps ...predicate.AuditLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AuditLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AuditLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AuditLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AuditLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AuditLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AuditLog).
func (m *AuditLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AuditLogMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.access_request != nil {
		fields = append(fields, auditlog.FieldAccessRequestID)
	}
	if m.action != nil {
		fields = append(fields, auditlog.FieldAction)
	}
	if m.actor_email != nil {
		fields = append(fields, auditlog.FieldActorEmail)
	}
	if m.actor_role != nil {
		fields = append(fields, auditlog.FieldActorRole)
	}
	if m.metadata != nil {
		fields = append(fields, auditlog.FieldMetadata)
	}
	if m.created_at != nil {
		fields = append(fields, auditlog.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AuditLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case auditlog.FieldAccessRequestID:
		return m.AccessRequestID()
	case auditlog.FieldAction:
		return m.Action()
	case auditlog.FieldActorEmail:
		return m.ActorEmail()
	case auditlog.FieldActorRole:
		return m.ActorRole()
	case auditlog.FieldMetadata:
		return m.Metadata()
	case auditlog.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AuditLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case auditlog.FieldAccessRequestID:
		return m.OldAccessRequestID(ctx)
	case auditlog.FieldAction:
		return m.OldAction(ctx)
	case auditlog.FieldActorEmail:
		return m.OldActorEmail(ctx)
	case auditlog.FieldActorRole:
		return m.OldActorRole(ctx)
	case auditlog.FieldMetadata:
		return m.OldMetadata(ctx)
	case auditlog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AuditLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case auditlog.FieldAccessRequestID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccessRequestID(v)
		return nil
	case auditlog.FieldAction:
		v, ok := value.(auditlog.Action)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAction(v)
		return nil
	case auditlog.FieldActorEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActorEmail(v)
		return nil
	case auditlog.FieldActorRole:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActorRole(v)
		return nil
	case auditlog.FieldMetadata:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMetadata(v)
		return nil
	case auditlog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AuditLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AuditLogMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AuditLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AuditLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AuditLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(auditlog.FieldMetadata) {
		fields = append(fields, auditlog.FieldMetadata)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AuditLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AuditLogMutation) ClearField(name string) error {
	switch name {
	case auditlog.FieldMetadata:
		m.ClearMetadata()
		return nil
	}
	return fmt.Errorf("unknown AuditLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AuditLogMutation) ResetField(name string) error {
	switch name {
	case auditlog.FieldAccessRequestID:
		m.ResetAccessRequestID()
		return nil
	case auditlog.FieldAction:
		m.ResetAction()
		return nil
	case auditlog.FieldActorEmail:
		m.ResetActorEmail()
		return nil
	case auditlog.FieldActorRole:
		m.ResetActorRole()
		return nil
	case auditlog.FieldMetadata:
		m.ResetMetadata()
		return nil
	case auditlog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown AuditLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AuditLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.access_request != nil {
		edges = append(edges, auditlog.EdgeAccessRequest)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AuditLogMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case auditlog.EdgeAccessRequest:
		if id := m.access_request; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AuditLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AuditLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AuditLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedaccess_request {
		edges = append(edges, auditlog.EdgeAccessRequest)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AuditLogMutation) EdgeCleared(name string) bool {
	switch name {
	case auditlog.EdgeAccessRequest:
		return m.clearedaccess_request
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AuditLogMutation) ClearEdge(name string) error {
	switch name {
	case auditlog.EdgeAccessRequest:
		m.ClearAccessRequest()
		return nil
	}
	return fmt.Errorf("unknown AuditLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AuditLogMutation) ResetEdge(name string) error {
	switch name {
	case auditlog.EdgeAccessRequest:
		m.ResetAccessRequest()
		return nil
	}
	return fmt.Errorf("unknown AuditLog edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                        Op
	typ                       string
	id                        *int
	email                     *string
	name                      *string
	password_hash             *string
	role                      *user.Role
	is_active                 *bool
	created_at                *time.Time
	updated_at                *time.Time
	clearedFields             map[string]struct{}
	submitted_requests        map[int]struct{}
	removedsubmitted_requests map[int]struct{}
	clearedsubmitted_requests bool
	managed_requests          map[int]struct{}
	removedmanaged_requests   map[int]struct{}
	clearedmanaged_requests   bool
	reviewed_requests         map[int]struct{}
	removedreviewed_requests  map[int]struct{}
	clearedreviewed_requests  bool
	done                      bool
	oldValue                  func(context.Context) (*User, error)
	predicates                []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// SetName sets the "name" field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// SetPasswordHash sets the "password_hash" field.
func (m *UserMutation) SetPasswordHash(s string) {
	m.password_hash = &s
}

// PasswordHash returns the value of the "password_hash" field in the mutation.
func (m *UserMutation) PasswordHash() (r string, exists bool) {
	v := m.password_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldPasswordHash returns the old "password_hash" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPasswordHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPasswordHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPasswordHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPasswordHash: %w", err)
	}
	return oldValue.PasswordHash, nil
}

// ResetPasswordHash resets all changes to the "password_hash" field.
func (m *UserMutation) ResetPasswordHash() {
	m.password_hash = nil
}

// SetRole sets the "role" field.
func (m *UserMutation) SetRole(u user.Role) {
	m.role = &u
}

// Role returns the value of the "role" field in the mutation.
func (m *UserMutation) Role() (r user.Role, exists bool) {
	v := m.role
	if v == nil {
		return
	}
	return *v, true
}

// OldRole returns the old "role" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldRole(ctx context.Context) (v user.Role, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRole is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRole requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRole: %w", err)
	}
	return oldValue.Role, nil
}

// ResetRole resets all changes to the "role" field.
func (m *UserMutation) ResetRole() {
	m.role = nil
}

// SetIsActive sets the "is_active" field.
func (m *UserMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *UserMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *UserMutation) ResetIsActive() {
	m.is_active = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddSubmittedRequestIDs adds the "submitted_requests" edge to the AccessRequest entity by ids.
func (m *UserMutation) AddSubmittedRequestIDs(ids ...int) {
	if m.submitted_requests == nil {
		m.submitted_requests = make(map[int]struct{})
	}
	for i := range ids {
		m.submitted_requests[ids[i]] = struct{}{}
	}
}

// ClearSubmittedRequests clears the "submitted_requests" edge to the AccessRequest entity.
func (m *UserMutation) ClearSubmittedRequests() {
	m.clearedsubmitted_requests = true
}

// SubmittedRequestsCleared reports if the "submitted_requests" edge to the AccessRequest entity was cleared.
func (m *UserMutation) SubmittedRequestsCleared() bool {
	return m.clearedsubmitted_requests
}

// RemoveSubmittedRequestIDs removes the "submitted_requests" edge to the AccessRequest entity by IDs.
func (m *UserMutation) RemoveSubmittedRequestIDs(ids ...int) {
	if m.removedsubmitted_requests == nil {
		m.removedsubmitted_requests = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.submitted_requests, ids[i])
		m.removedsubmitted_requests[ids[i]] = struct{}{}
	}
}

// RemovedSubmittedRequests returns the removed IDs of the "submitted_requests" edge to the AccessRequest entity.
func (m *UserMutation) RemovedSubmittedRequestsIDs() (ids []int) {
	for id := range m.removedsubmitted_requests {
		ids = append(ids, id)
	}
	return
}

// SubmittedRequestsIDs returns the "submitted_requests" edge IDs in the mutation.
func (m *UserMutation) SubmittedRequestsIDs() (ids []int) {
	for id := range m.submitted_requests {
		ids = append(ids, id)
	}
	return
}

// ResetSubmittedRequests resets all changes to the "submitted_requests" edge.
func (m *UserMutation) ResetSubmittedRequests() {
	m.submitted_requests = nil
	m.clearedsubmitted_requests = false
	m.removedsubmitted_requests = nil
}

// AddManagedRequestIDs adds the "managed_requests" edge to the AccessRequest entity by ids.
func (m *UserMutation) AddManagedRequestIDs(ids ...int) {
	if m.managed_requests == nil {
		m.managed_requests = make(map[int]struct{})
	}
	for i := range ids {
		m.managed_requests[ids[i]] = struct{}{}
	}
}

// ClearManagedRequests clears the "managed_requests" edge to the AccessRequest entity.
func (m *UserMutation) ClearManagedRequests() {
	m.clearedmanaged_requests = true
}

// ManagedRequestsCleared reports if the "managed_requests" edge to the AccessRequest entity was cleared.
func (m *UserMutation) ManagedRequestsCleared() bool {
	return m.clearedmanaged_requests
}

// RemoveManagedRequestIDs removes the "managed_requests" edge to the AccessRequest entity by IDs.
func (m *UserMutation) RemoveManagedRequestIDs(ids ...int) {
	if m.removedmanaged_requests == nil {
		m.removedmanaged_requests = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.managed_requests, ids[i])
		m.removedmanaged_requests[ids[i]] = struct{}{}
	}
}

// RemovedManagedRequests returns the removed IDs of the "managed_requests" edge to the AccessRequest entity.
func (m *UserMutation) RemovedManagedRequestsIDs() (ids []int) {
	for id := range m.removedmanaged_requests {
		ids = append(ids, id)
	}
	return
}

// ManagedRequestsIDs returns the "managed_requests" edge IDs in the mutation.
func (m *UserMutation) ManagedRequestsIDs() (ids []int) {
	for id := range m.managed_requests {
		ids = append(ids, id)
	}
	return
}

// ResetManagedRequests resets all changes to the "managed_requests" edge.
func (m *UserMutation) ResetManagedRequests() {
	m.managed_requests = nil
	m.clearedmanaged_requests = false
	m.removedmanaged_requests = nil
}

// AddReviewedRequestIDs adds the "reviewed_requests" edge to the AccessRequest entity by ids.
func (m *UserMutation) AddReviewedRequestIDs(ids ...int) {
	if m.reviewed_requests == nil {
		m.reviewed_requests = make(map[int]struct{})
	}
	for i := range ids {
		m.reviewed_requests[ids[i]] = struct{}{}
	}
}

// ClearReviewedRequests clears the "reviewed_requests" edge to the AccessRequest entity.
func (m *UserMutation) ClearReviewedRequests() {
	m.clearedreviewed_requests = true
}

// ReviewedRequestsCleared reports if the "reviewed_requests" edge to the AccessRequest entity was cleared.
func (m *UserMutation) ReviewedRequestsCleared() bool {
	return m.clearedreviewed_requests
}

// RemoveReviewedRequestIDs removes the "reviewed_requests" edge to the AccessRequest entity by IDs.
func (m *UserMutation) RemoveReviewedRequestIDs(ids ...int) {
	if m.removedreviewed_requests == nil {
		m.removedreviewed_requests = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.reviewed_requests, ids[i])
		m.removedreviewed_requests[ids[i]] = struct{}{}
	}
}

// RemovedReviewedRequests returns the removed IDs of the "reviewed_requests" edge to the AccessRequest entity.
func (m *UserMutation) RemovedReviewedRequestsIDs() (ids []int) {
	for id := range m.removedreviewed_requests {
		ids = append(ids, id)
	}
	return
}

// ReviewedRequestsIDs returns the "reviewed_requests" edge IDs in the mutation.
func (m *UserMutation) ReviewedRequestsIDs() (ids []int) {
	for id := range m.reviewed_requests {
		ids = append(ids, id)
	}
	return
}

// ResetReviewedRequests resets all changes to the "reviewed_requests" edge.
func (m *UserMutation) ResetReviewedRequests() {
	m.reviewed_requests = nil
	m.clearedreviewed_requests = false
	m.removedreviewed_requests = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	if m.password_hash != nil {
		fields = append(fields, user.FieldPasswordHash)
	}
	if m.role != nil {
		fields = append(fields, user.FieldRole)
	}
	if m.is_active != nil {
		fields = append(fields, user.FieldIsActive)
	}
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldEmail:
		return m.Email()
	case user.FieldName:
		return m.Name()
	case user.FieldPasswordHash:
		return m.PasswordHash()
	case user.FieldRole:
		return m.Role()
	case user.FieldIsActive:
		return m.IsActive()
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldEmail:
		return m.OldEmail(ctx)
	case user.FieldName:
		return m.OldName(ctx)
	case user.FieldPasswordHash:
		return m.OldPasswordHash(ctx)
	case user.FieldRole:
		return m.OldRole(ctx)
	case user.FieldIsActive:
		return m.OldIsActive(ctx)
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case user.FieldPasswordHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPasswordHash(v)
		return nil
	case user.FieldRole:
		v, ok := value.(user.Role)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRole(v)
		return nil
	case user.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	case user.FieldName:
		m.ResetName()
		return nil
	case user.FieldPasswordHash:
		m.ResetPasswordHash()
		return nil
	case user.FieldRole:
		m.ResetRole()
		return nil
	case user.FieldIsActive:
		m.ResetIsActive()
		return nil
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.submitted_requests != nil {
		edges = append(edges, user.EdgeSubmittedRequests)
	}
	if m.managed_requests != nil {
		edges = append(edges, user.EdgeManagedRequests)
	}
	if m.reviewed_requests != nil {
		edges = append(edges, user.EdgeReviewedRequests)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeSubmittedRequests:
		ids := make([]ent.Value, 0, len(m.submitted_requests))
		for id := range m.submitted_requests {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeManagedRequests:
		ids := make([]ent.Value, 0, len(m.managed_requests))
		for id := range m.managed_requests {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeReviewedRequests:
		ids := make([]ent.Value, 0, len(m.reviewed_requests))
		for id := range m.reviewed_requests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedsubmitted_requests != nil {
		edges = append(edges, user.EdgeSubmittedRequests)
	}
	if m.removedmanaged_requests != nil {
		edges = append(edges, user.EdgeManagedRequests)
	}
	if m.removedreviewed_requests != nil {
		edges = append(edges, user.EdgeReviewedRequests)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeSubmittedRequests:
		ids := make([]ent.Value, 0, len(m.removedsubmitted_requests))
		for id := range m.removedsubmitted_requests {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeManagedRequests:
		ids := make([]ent.Value, 0, len(m.removedmanaged_requests))
		for id := range m.removedmanaged_requests {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeReviewedRequests:
		ids := make([]ent.Value, 0, len(m.removedreviewed_requests))
		for id := range m.removedreviewed_requests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedsubmitted_requests {
		edges = append(edges, user.EdgeSubmittedRequests)
	}
	if m.clearedmanaged_requests {
		edges = append(edges, user.EdgeManagedRequests)
	}
	if m.clearedreviewed_requests {
		edges = append(edges, user.EdgeReviewedRequests)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeSubmittedRequests:
		return m.clearedsubmitted_requests
	case user.EdgeManagedRequests:
		return m.clearedmanaged_requests
	case user.EdgeReviewedRequests:
		return m.clearedreviewed_requests
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeSubmittedRequests:
		m.ResetSubmittedRequests()
		return nil
	case user.EdgeManagedRequests:
		m.ResetManagedRequests()
		return nil
	case user.EdgeReviewedRequests:
		m.ResetReviewedRequests()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
