// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cerberus/ent/accessrequest"
	"cerberus/ent/auditlog"
	"cerberus/ent/schema"
	"cerberus/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accessrequestFields := schema.AccessRequest{}.Fields()
	_ = accessrequestFields
	// accessrequestDescResource is the schema descriptor for resource field.
	accessrequestDescResource := accessrequestFields[3].Descriptor()
	// accessrequest.ResourceValidator is a validator for the "resource" field. It is called by the builders before save.
	accessrequest.ResourceValidator = accessrequestDescResource.Validators[0].(func(string) error)
	// accessrequestDescReason is the schema descriptor for reason field.
	accessrequestDescReason := accessrequestFields[4].Descriptor()
	// accessrequest.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	accessrequest.ReasonValidator = accessrequestDescReason.Validators[0].(func(string) error)
	// accessrequestDescManagerEmail is the schema descriptor for manager_email field.
	accessrequestDescManagerEmail := accessrequestFields[8].Descriptor()
	// accessrequest.ManagerEmailValidator is a validator for the "manager_email" field. It is called by the builders before save.
	accessrequest.ManagerEmailValidator = accessrequestDescManagerEmail.Validators[0].(func(string) error)
	// accessrequestDescCreatedAt is the schema descriptor for created_at field.
	accessrequestDescCreatedAt := accessrequestFields[9].Descriptor()
	// accessrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	accessrequest.DefaultCreatedAt = accessrequestDescCreatedAt.Default.(func() time.Time)
	// accessrequestDescUpdatedAt is the schema descriptor for updated_at field.
	accessrequestDescUpdatedAt := accessrequestFields[10].Descriptor()
	// accessrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	accessrequest.DefaultUpdatedAt = accessrequestDescUpdatedAt.Default.(func() time.Time)
	// accessrequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	accessrequest.UpdateDefaultUpdatedAt = accessrequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescActorEmail is the schema descriptor for actor_email field.
	auditlogDescActorEmail := auditlogFields[2].Descriptor()
	// auditlog.ActorEmailValidator is a validator for the "actor_email" field. It is called by the builders before save.
	auditlog.ActorEmailValidator = auditlogDescActorEmail.Validators[0].(func(string) error)
	// auditlogDescActorRole is the schema descriptor for actor_role field.
	auditlogDescActorRole := auditlogFields[3].Descriptor()
	// auditlog.ActorRoleValidator is a validator for the "actor_role" field. It is called by the builders before save.
	auditlog.ActorRoleValidator = auditlogDescActorRole.Validators[0].(func(string) error)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[5].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[4].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
