package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"cerberus/ent/accessrequest"
	"cerberus/graph"
	"cerberus/graph/model"
	"cerberus/internal/service"
	apperrors "cerberus/pkg/errors"
	"context"
	"fmt"
	"strconv"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	fmt.Printf("\n 3. Register resolver called")
	fmt.Printf("\n\n 4. Input received in resolver: %v", input)
	fmt.Println("5. Calling AuthService.Register")
	token, user, err := r.AuthService.Register(ctx, service.RegisterInput{
		Email:    input.Email,
		Name:     input.Name,
		Password: input.Password,
	})

	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		Token: token,
		User:  mapUser(user),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	token, user, err := r.AuthService.Login(ctx, service.LoginInput{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		Token: token,
		User:  mapUser(user),
	}, nil
}

// CreateAccessRequest is the resolver for the createAccessRequest field.
func (r *mutationResolver) CreateAccessRequest(ctx context.Context, input model.CreateAccessRequestInput) (*model.AccessRequest, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	requesterID, err := strconv.Atoi(claims.UserID)
	if err != nil {
		return nil, apperrors.Internal("invalid user id in token", err)
	}

	req, err := r.AccessRequestService.Create(
		ctx,
		input.Resource,
		input.Reason,
		input.ManagerEmail,
		claims.Email,
		claims.Role,
		requesterID,
	)
	if err != nil {
		return nil, err
	}

	return mapAccessRequest(req), nil
}

// UploadScreenshot is the resolver for the uploadScreenshot field.
func (r *mutationResolver) UploadScreenshot(ctx context.Context, requestID string, fileBase64 string, fileName string) (*model.AccessRequest, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	id, err := strconv.Atoi(requestID)
	if err != nil {
		return nil, apperrors.ValidationError("invalid request id")
	}

	req, err := r.AccessRequestService.UploadScreenshot(
		ctx, id, fileName, fileBase64,
		claims.Email, claims.Role,
	)
	if err != nil {
		return nil, err
	}

	return mapAccessRequest(req), nil
}

// ApproveRequest is the resolver for the approveRequest field.
func (r *mutationResolver) ApproveRequest(ctx context.Context, input model.ReviewRequestInput) (*model.AccessRequest, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	actorID, _ := strconv.Atoi(claims.UserID)
	requestID, err := strconv.Atoi(input.RequestID)
	if err != nil {
		return nil, apperrors.ValidationError("invalid request id")
	}

	req, err := r.AccessRequestService.Approve(
		ctx, requestID, actorID,
		input.Comment, claims.Email, claims.Role,
	)
	if err != nil {
		return nil, err
	}

	return mapAccessRequest(req), nil
}

// RejectRequest is the resolver for the rejectRequest field.
func (r *mutationResolver) RejectRequest(ctx context.Context, input model.ReviewRequestInput) (*model.AccessRequest, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	actorID, _ := strconv.Atoi(claims.UserID)
	requestID, err := strconv.Atoi(input.RequestID)
	if err != nil {
		return nil, apperrors.ValidationError("invalid request id")
	}

	req, err := r.AccessRequestService.Reject(
		ctx, requestID, actorID,
		input.Comment, claims.Email, claims.Role,
	)
	if err != nil {
		return nil, err
	}

	return mapAccessRequest(req), nil
}

// MarkUnderReview is the resolver for the markUnderReview field.
func (r *mutationResolver) MarkUnderReview(ctx context.Context, input model.ReviewRequestInput) (*model.AccessRequest, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	actorID, _ := strconv.Atoi(claims.UserID)
	requestID, err := strconv.Atoi(input.RequestID)
	if err != nil {
		return nil, apperrors.ValidationError("invalid request id")
	}

	req, err := r.AccessRequestService.MarkUnderReview(
		ctx, requestID, actorID,
		input.Comment, claims.Email, claims.Role,
	)
	if err != nil {
		return nil, err
	}

	return mapAccessRequest(req), nil
}

// UpdateUserRole is the resolver for the updateUserRole field.
// UpdateUserRole is the resolver for the updateUserRole field.
func (r *mutationResolver) UpdateUserRole(ctx context.Context, input model.UpdateUserRoleInput) (*model.User, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	userID, err := strconv.Atoi(input.UserID)
	if err != nil {
		return nil, apperrors.ValidationError("invalid user id")
	}

	// Pass actor context to service; service uses OPA to authorize.
	u, err := r.AccessRequestService.UpdateUserRole(
		ctx,
		userID,
		string(input.Role),
		claims.Email,
		claims.Role,
	)
	if err != nil {
		return nil, err
	}

	return mapUser(u), nil
}

// AccessRequest is the resolver for the accessRequest field.
func (r *queryResolver) AccessRequest(ctx context.Context, id string) (*model.AccessRequest, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	reqID, err := strconv.Atoi(id)
	if err != nil {
		return nil, apperrors.ValidationError("invalid id")
	}

	req, err := r.AccessRequestService.GetByID(ctx, reqID)
	if err != nil {
		return nil, err
	}

	return mapAccessRequest(req), nil
}

// AccessRequests is the resolver for the accessRequests field.
func (r *queryResolver) AccessRequests(ctx context.Context, filter *model.AccessRequestFilter, pagination *model.PaginationInput) (*model.AccessRequestConnection, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	page, pageSize := 1, 20
	if pagination != nil {
		page = pagination.Page
		pageSize = pagination.PageSize
	}

	var status *accessrequest.Status
	var requesterEmail, resource *string

	if filter != nil {
		if filter.Status != nil {
			s := accessrequest.Status(filter.Status.String())
			status = &s
		}
		requesterEmail = filter.RequesterEmail
		resource = filter.Resource
	}

	requests, total, err := r.AccessRequestService.List(
		ctx, requesterEmail, resource, status, page, pageSize,
	)
	if err != nil {
		return nil, err
	}

	nodes := make([]*model.AccessRequest, len(requests))
	for i, req := range requests {
		nodes[i] = mapAccessRequest(req)
	}

	return &model.AccessRequestConnection{
		Nodes: nodes,
		PageInfo: &model.PageInfo{
			Total:           total,
			HasNextPage:     page*pageSize < total,
			HasPreviousPage: page > 1,
		},
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	id, _ := strconv.Atoi(claims.UserID)
	u, err := r.AccessRequestService.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}

	return mapUser(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if claims.Role != "ADMIN" {
		return nil, apperrors.Forbidden("only admins can list all users")
	}

	users, err := r.AccessRequestService.ListUsers(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = mapUser(u)
	}
	return result, nil
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, requestID string) ([]*model.AuditLog, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	id, err := strconv.Atoi(requestID)
	if err != nil {
		return nil, apperrors.ValidationError("invalid request id")
	}

	logs, err := r.AccessRequestService.GetAuditLogs(ctx, id)
	if err != nil {
		return nil, err
	}

	result := make([]*model.AuditLog, len(logs))
	for i, l := range logs {
		result[i] = mapAuditLog(l)
	}
	return result, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
