// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldDepartment holds the string denoting the department field in the database.
	FieldDepartment = "department"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSubmittedRequests holds the string denoting the submitted_requests edge name in mutations.
	EdgeSubmittedRequests = "submitted_requests"
	// EdgeManagedRequests holds the string denoting the managed_requests edge name in mutations.
	EdgeManagedRequests = "managed_requests"
	// EdgeReviewedRequests holds the string denoting the reviewed_requests edge name in mutations.
	EdgeReviewedRequests = "reviewed_requests"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SubmittedRequestsTable is the table that holds the submitted_requests relation/edge.
	SubmittedRequestsTable = "access_requests"
	// SubmittedRequestsInverseTable is the table name for the AccessRequest entity.
	// It exists in this package in order to avoid circular dependency with the "accessrequest" package.
	SubmittedRequestsInverseTable = "access_requests"
	// SubmittedRequestsColumn is the table column denoting the submitted_requests relation/edge.
	SubmittedRequestsColumn = "requester_id"
	// ManagedRequestsTable is the table that holds the managed_requests relation/edge.
	ManagedRequestsTable = "access_requests"
	// ManagedRequestsInverseTable is the table name for the AccessRequest entity.
	// It exists in this package in order to avoid circular dependency with the "accessrequest" package.
	ManagedRequestsInverseTable = "access_requests"
	// ManagedRequestsColumn is the table column denoting the managed_requests relation/edge.
	ManagedRequestsColumn = "manager_id"
	// ReviewedRequestsTable is the table that holds the reviewed_requests relation/edge.
	ReviewedRequestsTable = "access_requests"
	// ReviewedRequestsInverseTable is the table name for the AccessRequest entity.
	// It exists in this package in order to avoid circular dependency with the "accessrequest" package.
	ReviewedRequestsInverseTable = "access_requests"
	// ReviewedRequestsColumn is the table column denoting the reviewed_requests relation/edge.
	ReviewedRequestsColumn = "reviewer_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldName,
	FieldPasswordHash,
	FieldRole,
	FieldDepartment,
	FieldIsActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Role defines the type for the "role" enum field.
type Role string

// RoleEMPLOYEE is the default value of the Role enum.
const DefaultRole = RoleEMPLOYEE

// Role values.
const (
	RoleEMPLOYEE    Role = "EMPLOYEE"
	RoleAPPROVER    Role = "APPROVER"
	RoleMANAGER     Role = "MANAGER"
	RoleADMIN       Role = "ADMIN"
	RoleSUPER_ADMIN Role = "SUPER_ADMIN"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleEMPLOYEE, RoleAPPROVER, RoleMANAGER, RoleADMIN, RoleSUPER_ADMIN:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// Department defines the type for the "department" enum field.
type Department string

// Department values.
const (
	DepartmentENGINEERING Department = "ENGINEERING"
	DepartmentSUPPORT     Department = "SUPPORT"
	DepartmentFINANCE     Department = "FINANCE"
	DepartmentHR          Department = "HR"
	DepartmentSALES       Department = "SALES"
)

func (d Department) String() string {
	return string(d)
}

// DepartmentValidator is a validator for the "department" field enum values. It is called by the builders before save.
func DepartmentValidator(d Department) error {
	switch d {
	case DepartmentENGINEERING, DepartmentSUPPORT, DepartmentFINANCE, DepartmentHR, DepartmentSALES:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for department field: %q", d)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByDepartment orders the results by the department field.
func ByDepartment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartment, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySubmittedRequestsCount orders the results by submitted_requests count.
func BySubmittedRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubmittedRequestsStep(), opts...)
	}
}

// BySubmittedRequests orders the results by submitted_requests terms.
func BySubmittedRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmittedRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagedRequestsCount orders the results by managed_requests count.
func ByManagedRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedRequestsStep(), opts...)
	}
}

// ByManagedRequests orders the results by managed_requests terms.
func ByManagedRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReviewedRequestsCount orders the results by reviewed_requests count.
func ByReviewedRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewedRequestsStep(), opts...)
	}
}

// ByReviewedRequests orders the results by reviewed_requests terms.
func ByReviewedRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewedRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSubmittedRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmittedRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubmittedRequestsTable, SubmittedRequestsColumn),
	)
}
func newManagedRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ManagedRequestsTable, ManagedRequestsColumn),
	)
}
func newReviewedRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewedRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReviewedRequestsTable, ReviewedRequestsColumn),
	)
}
