// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessRequest is the predicate function for accessrequest builders.
type AccessRequest func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
